### ISSUE TITLE
Suggest Folders by Email Thread

### ISSUE THREAD

**Issue by mjklemm** [RealRaven2000/QuickFolders#196] opened 2021-08-23 08:22 UTC
When hitting `M` to file a message, QuickFolders uses the last folder name as the default suggestion.  It would be good if that suggestion could be made such that it suggests the name of the folder that the last message of that thread was filed to.

**Comment by RealRaven2000** [comment] 2021-08-23 12:56
I have been thinking about something like this for quite a while - the obvious problem here is that the Add-on would need to search across all the folders (even when using the GLODA internal database) - and it might add a long time to the search. Ideally we should have this as a filter action to be executed automatically on incoming mail - but I will look into it to see how to do this and maybe make some tests, I would definitely agree that I would like to know where the other mails in the thread have landed (bear in mind it can already spread across multiple locations)

I think I looked into the "thread-identity" of a message before but that was a long time ago.

**Comment by RealRaven2000** [comment] 2021-08-23 13:07
One thing I find but only in mails written in Thunderbird are fields `In-Reply-To` and `References` :

![image](https://user-images.githubusercontent.com/6314674/130451383-30913b3d-ccac-4ae2-8be9-73054f361a07.png)

see also:
https://stackoverflow.com/questions/45690336/do-all-email-clients-use-in-reply-to-field-in-email-header

**Comment by RealRaven2000** [comment] 2021-08-23 14:18
So I was told "You don't need to search in-reply-to in gloda, it already has its own conversation definition", so I found this, as a starting point in GlodaDataModel.jsm:

https://searchfox.org/comm-central/source/mailnews/db/gloda/modules/GlodaDataModel.jsm#662

not sure how to access that from (experimental) code yet, but I am sure I will find an example or two in core.

**Comment by mjklemm** [comment] 2021-08-23 14:20
I have replied in Outlook to an email written with Thunderbird.  It seems that Outlook added the appropriate headers:

![image](https://user-images.githubusercontent.com/5994372/130463116-adcb748e-b39f-41c3-be75-90e71c1b4e72.png)

Also Mutt (to no surprise :-)) added a reference:

![image](https://user-images.githubusercontent.com/5994372/130463181-03aecf8a-4eeb-4f4d-9381-a24528231654.png)

That's pretty much all MUA that I care for, but if needed, I can test things like Web-based Outlook, too.

Ultimately, if the email comes in and cannot connect to related email thread because the sending MUA did not add the proper header, then there's nothing you can do.  Thunderbird, Outlook and ClearContext (also provides messages filing) then just give up and are not able to provide thread-based features to the user.

**Comment by RealRaven2000** [comment] 2021-09-09 11:21
Just going over my ever growing bug list I just noticed this is a duplicate of #95 - let's keep discussing over there, closing this one!

**Closed by RealRaven2000** 2021-09-09 11:21 UTC
Labels: enhancement
