### ISSUE TITLE
All Text in popup menus (subfolders / commands) is missing

### ISSUE THREAD

**Issue by PremPa** [RealRaven2000/QuickFolders#333] opened 2022-12-22 08:43 UTC
![Appunti01](https://user-images.githubusercontent.com/61465669/209093412-8effa0bf-b122-483b-9f8e-55ecd2d96803.jpg)

I tried to reconstruct all the tabs but nothing changed

**Comment by kiki78** [comment] 2022-12-22 09:07
Same for me since this morning with 5.15.

**Comment by mrtnhmtz** [comment] 2022-12-22 09:35
Same for me after update of QuickFolder this morning to version 5.15 on TB 102.4.2: The menu is opened and seems to work but shows no text after Ctrl+M and Ctrl-J are used.

**Comment by michauk** [comment] 2022-12-22 09:57
Same with ctrl-J ctrl-M, quite a problem. I've downgraded to 5.14 : https://github.com/RealRaven2000/QuickFolders/releases/download/5.14/QuickFolders-mx-5.14.xpi

**Comment by RealRaven2000** [comment] 2022-12-22 10:10
Thanks for reporting, this is a regression from the work in issue #329. I set the font size and while testing forgot that the default here is 0 (so setting a font size to 12 would have fixes this too):

![image](https://user-images.githubusercontent.com/6314674/209110925-45f5e6df-c9cb-4b97-9ea1-3cdecc156785.png)

here is a version with a quick fix:

[QuickFolders-mx-5.15.1pre1.zip](https://github.com/RealRaven2000/QuickFolders/files/10285930/QuickFolders-mx-5.15.1pre1.zip)

To test this version, download the zip file above and drag it into Thunderbird Add-ons Manager (without extracting its contents)

**Comment by kiki78** [comment] 2022-12-22 10:28
Quick fix wok also for me. Thank you Axel.
Regards,

**Comment by ggianna** [comment] 2022-12-22 10:57
I confirm the bug and the workaround. Thank you, Axel.

**Comment by RealRaven2000** [comment] 2022-12-22 14:09
please leave issue open until official version has landed on ATN for better visibility  to other users.

**Comment by PremPa** [comment] 2022-12-22 16:05
> please leave issue open until official version has landed on ATN for better visibility to other users.

Ok, sorry for my rush ^_^"

**Comment by RealRaven2000** [comment] 2022-12-22 16:11
> > please leave issue open until official version has landed on ATN for better visibility to other users.
> 
> Ok, sorry for my rush ^_^"

No worries - 5.15.1 just has been reviewed and published on ATN: 
https://addons.thunderbird.net/en-US/thunderbird/addon/quickfolders-tabbed-folders/versions/?page=1#version-5.15.1

so closing is alright now. :)

**Closed by RealRaven2000** 2022-12-22 16:11 UTC
Labels: bug
