### ISSUE TITLE
Updating Quickfolders hangs TB

### ISSUE THREAD

**Issue by Thefaroah** [RealRaven2000/QuickFolders#298] opened 2022-08-17 20:01 UTC
I reported this before but can't seem to locate it.
Updated QF and TB hangs. A new tab opens with QF info and appears to be loading forever. Never ends.
Must kill TB via Task Manager.
BTW...QF seems to update OK.

**Comment by RealRaven2000** [comment] 2022-08-17 20:27
that's strange.  it's likely the version history.  the is a jQuery script on there they I suspect may be the culprit.  I will pull that from the page as soon as I am back in the office...

**Comment by RealRaven2000** [comment] 2022-08-17 20:34
btw you can visit the page here:

https://quickfolders.org/version.html#5.12

but there are additional querystring parameters depending on your license status.

**Comment by RealRaven2000** [comment] 2022-08-17 20:47
can you close the tab?

**Comment by Thefaroah** [comment] 2022-08-17 20:52
No. Can't close any tabs. Can't click on anything at all. TB is locked tight.

**Comment by RealRaven2000** [comment] 2022-08-17 21:36
start up in safe mode first - if you used 91 it may be the upgrade to 102
and a ton of data migration...

**Comment by Thefaroah** [comment] 2022-08-17 22:02
Should have noted this before. I'm on TB 102.1.2 (64-bit). Been using 102 very some time now. And it has some issues, separate from QF.
Using safe mode doesn't help. When the problem occurs, I kill TB and do a normal restart. QF behaves OK then.
Bottom line:
1. Check for add-on updates.
2. 1 update available (QF)
3. Click the update icon.
4. QF tab opens.
5. Bam... TB hung up.
6. Kill, restart.

**Comment by RealRaven2000** [comment] 2022-08-18 10:45
I had performance issues with QuickFolders 5.10.3 and then opened  [issue #283] which was closed in 5.11 - some more minor performance tweaks for the current version 5.12, and it operates fine here on my system with 1500 folders. There were some problems with [unwanted folder cache invalidations](https://bugzilla.mozilla.org/show_bug.cgi?id=1776280) caused by the folder tree (will be fixed in Thunderbird 102.2) - one workaround was hiding the tree using F9. There is an explanation in bug 1778888 ([comment 10](https://bugzilla.mozilla.org/show_bug.cgi?id=1778888#c10)) - fix will also arrive in 102.2. It would be interesting if this fixes the performance for you.

There is a [release candidate](https://ftp.mozilla.org/pub/thunderbird/candidates/102.2.0-candidates/build1/) but unfortunately there is a regression with the error console, so we won't be able to fully profile what happens with that version.

Do you have any special non-standard accounts (that are not POP3 or IMAP) that might do non-standard things?

Any other Add-ons dealing with folders?

If you have the latest version (5.12) you can run some performance tests (start with QF disabled and then switch it on top see what happens).

QuickFolders Settings / Advanced / Debug Mode/

If you right-click Debug Mode you can set this additional setting:

![DCcOhnWpns7qAIyu](https://user-images.githubusercontent.com/6314674/185376730-33465b9e-1c2f-47ab-9c31-632ab7645409.png)

`extensions.quickfolders.debug.performance = true`

![ZTXQcE0VZ6HE01RL](https://user-images.githubusercontent.com/6314674/185376764-a4b9c349-d5c2-44c3-9bef-bf6a4a71c9c8.png)


this adds some stopwatch (time) measurements to the error console (Ctrl+Shift+J)

Do you have many visible tabs on the QuickFolders toolbar? (You can use Categories to narrow them down in case you do not know)

**Comment by Thefaroah** [comment] 2022-08-18 11:14
The only real issue I have is what occurs after I apply a QF update. It hangs TB.
I know there's a bit of a delay loading QF tabs at startup, but that (IMHO) is a very minor issue.
Other than that, it runs well.
I'll try you're suggestions before applying any updates when they become available.

**Comment by RealRaven2000** [comment] 2022-08-18 19:06
Can you try setting:

`extensions.quickfolders.hideVersionOnUpdate = true`

**Comment by ilNebbioso** [comment] 2022-08-18 20:12
>  some more minor performance tweaks for the current version 5.12, and it operates fine here on my system with 1500 folders. 

I think I have the same minor issue too (TB 102.1.2 + QF 5.12 + SSD 512GB) while:
- passing near the folder tree while dragging messages. 
- sometimes (not always) when preparing the view of a message/folder
But 5.12 is much much much better the 5.11!

I actually got a 70GB local folder, 625 folders. Maybe this could help?

**Comment by RealRaven2000** [comment] 2022-08-18 21:16
> I think I have the same minor issue too (TB 102.1.2 + QF 5.12 + SSD 512GB) while:
> 
> * passing near the folder tree while dragging messages.
> * sometimes (not always) when preparing the view of a message/folder
>   But 5.12 is much much much better the 5.11!
> 
> I actually got a 70GB local folder, 625 folders. Maybe this could help?

I encourage you to look at the JavaScript error console with  the [debug settings above](https://github.com/RealRaven2000/QuickFolders/issues/298#issuecomment-1219342856) enabled. It sums up various operations. If you want an instant speed boost, hide the folder tree using [F9]. I would be super interested whether this version fixes it for you:

https://ftp.mozilla.org/pub/thunderbird/candidates/102.2.0-candidates/build1/

only problem: this one has a problem with the error console (I raised [bug 1785222](https://bugzilla.mozilla.org/show_bug.cgi?id=1785222) for this regression which I hope they fix before they actually release 102.2; possibly in the next release candidate). The good thing of this version is that you can open your regular profile without "conversion penalty" - anything that starts with 102 won't change any data formats.

**Comment by ilNebbioso** [comment] 2022-08-18 21:57
> I encourage you to look at the JavaScript error console with the [debug settings above](https://github.com/RealRaven2000/QuickFolders/issues/298#issuecomment-1219342856) enabled. It sums used time of up various operations. If you want an instant speed boost, hide the folder tree using [F9]. 

I enabled the debug console and hidden the folder tree with F9. 
No other plugin was enabled during these test.

Then, I tried to drag single message from my Inbox as I would like to move somewhere. 4 times it seems everything ok, while about with the 5th (sometimes it did at 3th, sometime else as 6th), I found these row in the console.

Unfortunally I cannot undestand quite nothing on the contents, so sorry if I pointed you something not useful.

As you can read, I have about 50 quickfolders (I do not find confortable with categories, while I use a lot QuickMove/QuickJump and dragging to these QuickFolders as well).

> I would be super interested whether this version fixes it for you: https://ftp.mozilla.org/pub/thunderbird/candidates/102.2.0-candidates/build1/

I ask you a confirmation: do you want that I install TB 102.2.0 RC (https://ftp.mozilla.org/pub/thunderbird/candidates/102.2.0-candidates/build1/win64/lt/ in my case) over the 102.1.2 to see if, with a normal session of QF5.12 (not in debug mode), this solves?

Here below what I found into my console during the tests:

*** begin console ***

<Provider> does not support changing "store" on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions. react-redux.js:881:13

downloadable font: failed to start download (font-family: "Lato" style:normal weight:400 stretch:100 src index:0): content blocked source: https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap 


Starting updateFolders - Active Categories: __ALL 

quickfolders-interface.js:571:15
QuickFolders 23:41:10.89  [503 ms]   

 updateFolders(rebuildCategories: false, minimal: true) - Number of Folders = 51 quickfolders-util.js:1164:13

QuickFolders 23:41:17.361  [7272 ms]   
 51 of 51 tabs refreshed on toolbar [minimalUpdate]. quickfolders-util.js:1164:13

QuickFolders.Interface.updateFolders(rebuildCat = false, minimal = true)
 51 folders took: [7275 ms]
 
 QuickFolders 23:42:25.569  [68208 ms]   
 Persisted tab category: __ALL
 
 downloadable font: failed to start download (font-family: "Lato" style:normal weight:400 stretch:100 src index:0): content blocked source: https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap

QuickFolders 23:43:8.298  [42729 ms]   
 setFolderUpdateTimer(item):Posta in arrivo quickfolders-util.js:1164:13

QuickFolders 23:43:8.299  [1 ms]   
 Folder Tab Select Timer ID: 194 quickfolders-util.js:1164:13

QuickFolders 23:43:8.299  [0 ms]   
 Setting Update Timer (after timer 188 expired), new Timer: 194 quickfolders-util.js:1164:13
Starting updateFolders - Active Categories: __ALL quickfolders-interface.js:571:15

QuickFolders 23:43:8.801  [502 ms]   
 updateFolders(rebuildCategories: false, minimal: true) - Number of Folders = 51 quickfolders-util.js:1164:13

QuickFolders 23:43:14.824  [6023 ms]   
 51 of 51 tabs refreshed on toolbar [minimalUpdate]. quickfolders-util.js:1164:13

QuickFolders.Interface.updateFolders(rebuildCat = false, minimal = true)
 51 folders took: [6023 ms]

*** end console ***

Thank you for your help and support!

**Comment by RealRaven2000** [comment] 2022-08-18 22:11
> I ask you a confirmation: do you want that I install TB 102.2.0 RC (https://ftp.mozilla.org/pub/thunderbird/candidates/102.2.0-candidates/build1/win64/lt/ in my case) over the 102.1.2 to see if, with a normal session of QF5.12 (not in debug mode), this solves?

no I would recommend doing a **custom install** into a separate folder instead. For instance C:\Program Files\Mozilla thunderbird 102.2\ - you can change the Command line to "(program path" -ProfileManager if you like so you can force the new version to use the same profile as normal. When you go through the installation do not register as default application. Now you can A/B compare with the same profile and go back to the regular version - just don't use them at the same time!

**Comment by ilNebbioso** [comment] 2022-08-18 22:59
> no I would recommend doing a **custom install** into a separate folder instead. For instance C:\Program Files\Mozilla thunderbird 102.2\ - you can change the Command line to "(program path" -ProfileManager if you like so you can force the new version to use the same profile as normal. When you go through the installation do not register as default application. Now you can A/B compare with the same profile and go back to the regular version - just don't use them at the same time!

First of all thank you **SO** much for addressing me in the right way!

I confirm you TB 102.2.0RC works a lot better with QF 5.12: 
- QF initialize much faster, 
- TB doesn't have any problem with recent folders,
- I didn't experienced, in a test long as the previous, any lag while dragging/opening messages

**Comment by RealRaven2000** [comment] 2022-08-18 23:18
> I confirm you TB 102.2.0RC works a lot better with QF 5.12:
> 
> * QF initialize much faster,
> * TB doesn't have any problem with recent folders,
> * I didn't experienced, in a test long as the previous, any lag while dragging/opening messages

Nice one! once they fix the logging bug (maybe in 102.2 RC build2 I hope) we can have some measurements for comparison. btw (with about 25 visible tabs) I get update Folders (which repaints the tabs) taking about 350ms on average but some outliers take 2500-3000ms. But I think updating the tabs doesn't really slow down Tb  operations. If it does maybe I can break it up into doing 10 at a time or something?

**Comment by RealRaven2000** [comment] 2022-08-18 23:20
one more tip on the error console - for (experimental) Add-ons like QF you don't really need to enable content logging, only info, warnings and errors.

**Comment by ilNebbioso** [comment] 2022-08-19 21:17
@RealRaven2000 since 24 hrs I heavyly using TB 102.2.0RC + QF 5.12. 

I didn't have find any issue until now.

I also experienced another little bug I wasn't sure was caused by QF, who actually seems disappeared. Can you confirm was QF related?
Sometimes, when moving a message using QuickFolder > tab, the folder I was showing hid all the messages like a filter was applied.
The workaround was easy: simply click on any other folder to go back to the original one (also using QF tabs) in order to have back all the remaining messages in the folder.

**Comment by RealRaven2000** [comment] 2022-08-19 21:28
> I also experienced another little bug I wasn't sure was caused by QF, who actually seems disappeared. Can you confirm was QF related? Sometimes, when moving a message using QuickFolder > tab, the folder I was showing hid all the messages like a filter was applied. The workaround was easy: simply click on any other folder to go back to the original one (also using QF tabs) in order to have back all the remaining messages in the folder.

Can't confirm that - were you holding down any modifier keys? (Ctrl / Shift or alt)?

**Comment by ilNebbioso** [comment] 2022-08-19 21:39
> Can't confirm that - were you holding down any modifier keys? (Ctrl / Shift or alt)?

No, I was just doing drag'n'drop with a simple message.

But, on the other hand, it happened (also in this case sometimes) dragging more messages selected with CTRL or SHIFT. Surely, I wasn't hitting nothing while dropping.

**Comment by Thefaroah** [comment] 2022-08-20 16:03
My original problem (the reason for this post) has apparently been fixed with QF ver 5.12.1
Applied the update and no TB hangs. Noticed the new open tab, which had occurred prior to 5.12.1, did not happen.
Yahoo. And many thanks.

**Comment by RealRaven2000** [comment] 2022-08-20 16:54
> My original problem (the reason for this post) has apparently been fixed with QF ver 5.12.1 Applied the update and no TB hangs. Noticed the version history tab, which had occurred prior to 5.12.1, did not happen. Yahoo. And many thanks.

this is interesting - so it really is the version history page. (I disable it by default now when QuickFolders updates - setting is on QF Settings / Advanced). The question is, does Thunderbird slow down if you look at it later (e.g. by clicking the version number on the QF settings dialog)?

![image](https://user-images.githubusercontent.com/6314674/185758072-73919fed-e843-430d-9d71-c58322f417d8.png)

one would think loading a simple web site shouldn't hold up the main thread this significantly...

**Comment by Thefaroah** [comment] 2022-08-20 17:25
Tried it via clicking the version number in Quickfolder options:
KAPOW... TB hangs up tight.
Kill TB, restart, and all is OK.

**Comment by Thefaroah** [comment] 2022-08-20 17:29
BTW... Somehow strayed away from the original issue, so I reset all suggested settings you mentioned earlier.
If  it can help, should I set them back?

**Comment by ilNebbioso** [comment] 2022-08-20 18:43
> Tried it via clicking the version number in Quickfolder options: KAPOW... TB hangs up tight. Kill TB, restart, and all is OK.

On TB 102.2.0RC + QF 5.12 it opens as expected. The same with TB 102.2.0RC+QF 5.12.1pre9

**Comment by Thefaroah** [comment] 2022-08-20 21:06
So, a TB issue? I'll wait for 102.2 to be released. A bit gun shy with release channel.
Too bad it appears your problem when it's not.

**Comment by ilNebbioso** [comment] 2022-08-26 08:52
> I also experienced another little bug I wasn't sure was caused by QF, who actually seems disappeared. Can you confirm was QF related?
> Sometimes, when moving a message using QuickFolder > tab, the folder I was showing hid all the messages like a filter was applied.
> The workaround was easy: simply click on any other folder to go back to the original one (also using QF tabs) in order to have back all the remaining messages in the folder.

@RealRaven2000 I'm going to open a new thread about this: actually I'm using TB 102.2.0 + QF 5.12.1 (no other Extension activated) and sometimes it happens.

**Comment by RealRaven2000** [comment] 2022-08-26 09:09
> > I also experienced another little bug I wasn't sure was caused by QF, who actually seems disappeared. Can you confirm was QF related?
> > Sometimes, when moving a message using QuickFolder > tab, the folder I was showing hid all the messages like a filter was applied.
> > The workaround was easy: simply click on any other folder to go back to the original one (also using QF tabs) in order to have back all the remaining messages in the folder.
> 
> @RealRaven2000 I'm going to open a new thread about this: actually I'm using TB 102.2.0 + QF 5.12.1 (no other Extension activated) and sometimes it happens.

yes, open another bug. I think if there are update issues, we may have to look at this with @jobisoft because he has a better chance of understanding the process of Thunderbird "doing" the actual update. The only thing I noticed is that Tb 102.2 has fixed the "slow folder tree" issue which bogged down the UI while QuickFolders was running (and was especially noticable when using the Recent Folders tab) - see #283

**Comment by RealRaven2000** [comment] 2022-08-26 10:05
> > My original problem (the reason for this post) has apparently been fixed with QF ver 5.12.1 Applied the update and no TB hangs. Noticed the version history tab, which had occurred prior to 5.12.1, did not happen. Yahoo. And many thanks.
> 
> this is interesting - so it really is the version history page. (I disable it by default now when QuickFolders updates - setting is on QF Settings / Advanced). The question is, does Thunderbird slow down if you look at it later (e.g. by clicking the version number on the QF settings dialog)?
> 
> ![image](https://user-images.githubusercontent.com/6314674/185758072-73919fed-e843-430d-9d71-c58322f417d8.png)
> 
> one would think loading a simple web site shouldn't hold up the main thread this significantly...

@Thefaroah  So I am going to close this bug as resolved (by the new default that hides the version history). I opened a new issue #302 and see who else replies. I wasn't on the Add-on developers call this week, I will try to think of bringing the topic up next Monday.

**Closed by RealRaven2000** 2022-08-26 10:05 UTC

**Comment by RealRaven2000** [comment] 2022-10-11 07:51
make a backup of your session.json file we will have a look later.  ( not
quite sure whether that's the exact file name, but this stores your tabs)
