### ISSUE TITLE
"Customize Icon..." context menu item disappears mysteriously

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/QuickFolders#430] opened 2023-11-07 22:21 UTC
Thunderbird 115.4.1 / QuickFolders 6.3 / Windows 10 Pro

Not sure why, but after some time, the "Customize Icon..." item / "QuickFolders" sub-menu disappears from the folder context-menu.  I'm left with only a "Remove Customized Icon" item (directly in the context menu) on folders that have a customized icon.

If I restart TB (or if I just disable/enable the add-on), the menu item / sub-menu is back, only to disappear again after a while.

**Comment by RealRaven2000** [comment] 2023-11-07 23:30
ok thanks, I will look into this. seems to be reproducable...

**Comment by RealRaven2000** [comment] 2023-11-07 23:51
I think I know what happens. the menu remembers removing the "remove icon" menu item= when you right-click any other folder (that has no icon set).

try this version:
[QuickFolders-mx-6.3.1pre3.zip](https://github.com/RealRaven2000/QuickFolders/files/13290329/QuickFolders-mx-6.3.1pre3.zip)

----

to install the test version, download the zip file and then drag the file into Thunderbird Add-ons Manager (do not extract contents).

**Comment by goozak** [comment] 2023-11-08 14:10
> the menu remembers removing the "remove icon" menu item

Before updating with the `pre` version, I can tell you that this is not the case.  Right-clicking any number of folders shows the correct option.  It only stops working 'after a while'...

**Comment by RealRaven2000** [comment] 2023-11-08 21:01
> > the menu remembers removing the "remove icon" menu item
> 
> Before updating with the `pre` version, I can tell you that this is not the case. Right-clicking any number of folders shows the correct option. It only stops working 'after a while'...

Actually I was wrong, it happens when you right-click something that is _neither a folder nor a server_. I am  not sure what that might be but the logic points to that this is what happened. And I am not sure whether this is just right-clicking in the folder pane only or whether it can be triggered by right-clicking something else (e.g. on an email). I am pretty sure that 6.3.1pre3 fixes it.

**Comment by goozak** [comment] 2023-11-08 21:03
Yeah, I've been running `6.3.1pre3` all day, and I still have the correct menu items.  👍

**Comment by RealRaven2000** [comment] 2023-12-04 17:10
Fixed in 6.4 released on 04/12/2023

**Closed as completed by RealRaven2000** 2023-12-04 17:10 UTC
Labels: ESR 115
