### ISSUE TITLE
New toolbar appearing in message-headers cannot be closed

### ISSUE THREAD

**Issue by typoworx-de** [RealRaven2000/QuickFolders#173] opened 2021-07-06 07:29 UTC
After updating there is appearing a new toolbar above message inside the message-headers context. The "x" button (closing?) does not seem to have any function and does not work.

I'm unable to disable this toolbar I never had activated before and I don't like to use it as I only want to use the main-toolbar in Thunderbird menu-context.

How can this be disabled? Tried some settings in options but neither found any setting that obviously can remove this nor I randomly found any checkbox to disable/remove it.

![image](https://user-images.githubusercontent.com/1282298/124559925-85da1c80-de3c-11eb-9b69-97a9242eb1eb.png)

**Comment by typoworx-de** [comment] 2021-07-06 07:39
Okay for some reason it disappeared after restarting Thunderbird. Hoping it's not appearing again. But still I'm wondering the "x" Close button has not function? I think it should ask for closing and removing this toolbar. But theres simply no function behind.

**Comment by RealRaven2000** [comment] 2021-07-06 09:47
So the close button works for me (it's a temporary close, which means the toolbar comes back after restart). To disable it **permanently** you can use Advanced / Display the Toolbar - uncheck this checkbox:

![image](https://user-images.githubusercontent.com/6314674/124578531-34368f80-de46-11eb-8ba7-ddd8d36a5b1c.png)

I can imagine that it behaved like this (unexpectedly) when the latest version QuickFolders 5.6.5 was installed, so I checked whether this behavior is reproduceable:

When I update QuickFolders to a new version, the toolbar briefly appears but is then removed. ONce you have disabled the toolbar as described above, can you test this by installing this test version?

[QuickFolders-mx-5.6.6pre2.zip](https://github.com/RealRaven2000/QuickFolders/files/6769046/QuickFolders-mx-5.6.6pre2.zip)

To install this, download the zip file. then drag the zip file into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment] 2021-07-23 15:09
I believe this was fixed with the release of 5.6.6. Feel free to reopen it if you can reproduce it with that.

**Closed by RealRaven2000** 2021-07-23 15:09 UTC
