### ISSUE TITLE
Folder list menu under tabs does not scroll

### ISSUE THREAD

**Issue by swolh** [RealRaven2000/QuickFolders#77] opened 2020-11-23 18:08 UTC
WHen you try to drag a message to a folder by dragging it to the a folder tab, and then dragging it down the folder list that appears under that tab - and the list of folders that opens is longer than fits top to bottom on the screen - as you drag the message down the list to get to a folder that's at the bottom of the list and not showing on screen .... when you get to the down arrow at the bottom of the list, the list does not scroll to the folders that are off screen at the bottom.

**Comment by RealRaven2000** [comment] 2020-11-23 22:24
This is a duplicate of issue #5 
long standing and hard to fix

**Comment by RealRaven2000** [comment] 2021-08-31 11:08
Closing as duplicate of #5

more info + comments there.

**Closed by RealRaven2000** 2021-08-31 11:08 UTC
