### ISSUE TITLE
quickMove - no folder suggestions while viewing in searched list (search results / open msg in conversation) - Tb78

### ISSUE THREAD

**Issue by fredstluka** [RealRaven2000/QuickFolders#136] opened 2021-04-09 21:41 UTC
I use Shift-M, Shift-T, and Shift-J all the time.  Mostly when looking at a list of emails.

But every now and then, I hit Cmd-Shift-O when looking at a list of emails, to see the entire threaded conversation across multiple folders.

While looking at that threaded conversation, I try to use Shift-M, Shift-T, or Shift-J, to move or copy one of the messages of the thread to a different folder.  Or to jump to that folder.

In that case, Shift-M, Shift-T, or Shift-J pops up a text box as usual, but when I type into the text box, it shows no dropdown menu.  And when I hit down-arrow, it shows the previous folder that I did a move, copy or jump to.  Totally ignoring the chars I've now typed into the text box.

Odd...
--Fred

[4/9/2012 Edit]
My workaround is to right-click the message in the conversation, and choose "Open Message in Containing Folder".  Then use Shift-M, Shift-T, or Shift-J as usual.

--Fred

**Comment by RealRaven2000** [comment] 2021-04-12 19:25
> I use Shift-M, Shift-T, and Shift-J all the time. Mostly when looking at a list of emails.
> 
> But every now and then, I hit Cmd-Shift-O when looking at a list of emails, to see the entire threaded conversation across multiple folders.

Ok. I never used Cm=Shift-O (my Windows PC doesn't have a Cmd key) but now I believe I understand it's a quickSearch turned into a virtual mail search list? Basically something that comes up after clicking "Open email as list"? I have changed the title along those lines so be more accessible. describing a bug based on three keyboard shortcuts is a nightmare and probably didn't motivate me to read your description in full detail. (Plus that fact that you tend to submit multiple issues at once which overwhelms my capacity)

![image](https://user-images.githubusercontent.com/6314674/114449550-c4a95f00-9bcc-11eb-8cb2-7dfe56f1bd26.png)

And you want to move mails from there... I think Thunderbird (or my code) somehow has problems determining the original folder "we are in now". I need to check what I am doing here, but generally it should get the source folder(s) from the actual emails hightlighted. Except it does this really STUPID assumption that the first email in the list gives the folder (and that the other highlighted emails are in the same folder).

At least that is my understanding of now, please correct me if I am wrong...

**Comment by RealRaven2000** [comment] 2021-04-13 11:14
Ok, I can reproduce but only on Thunderbird 78. In error console I see this exception:

![image](https://user-images.githubusercontent.com/6314674/114543797-9883f180-9c51-11eb-9687-606ea5b71476.png)

So that's definitely a great starting point to work from. usually it's a good idea to look into JS error console when something stops working first.

**Comment by RealRaven2000** [comment] 2021-04-13 11:18
So, this seems to be a side effect of the new feature to exclude accounts from the search results. or rather the feature not to allow moving from the current account to another, here are the lines where it fails:

```
  if (isQuickJumpOrMove) {
    currentFolder = util.CurrentFolder;
    if (!currentFolder) isQuickJumpOrMove = false; // can't determine current account
    currentServer = currentFolder.server ? currentFolder.server.key : null;
    quickMoveSettings.loadExclusions(); // prepare list of servers to omit
  }
```

even if I fix this it will probably break the "don't move mail to other servers" feature. It's tricky because you may have multiple mails in different accounts selected...

**Comment by RealRaven2000** [comment] 2021-04-13 11:27
quick fix version for Thunderbird 78:

[QuickFolders-wx-5.5pre3.zip](https://github.com/RealRaven2000/QuickFolders/files/6303326/QuickFolders-wx-5.5pre3.zip)

Note: this should still honor the excluded accounts, but the advanced search setting "Only show results from current mail account" will not work because in a search there is no current folder, and this is what that setting is based on!

**Comment by fredstluka** [comment] 2021-04-16 00:49
Axel,

> Ok. I never used Cm=Shift-O (my Windows PC doesn't have a Cmd key) but 
> now I believe I understand it's a quickSearch turned into a virtual 
> mail search list?
>
No.  It does the menu action: Message | Open in Conversation.
Probably Ctrl-Shift-O on Windows.

> Basically something that comes up after clicking "Open email as list"? 
> I have changed the title along those lines so be more accessible.
>

I think you should change the title to:

Shift-M, Shift-T, and Shift-J misbehave when viewing mails
in a "conversation" window...

> describing a bug based on three keyboard shortcuts is a nightmare and 
> probably didn't motivate me to read your description in full detail.
>

Sorry about that!  Instead of "Shift-M, Shift-T, and Shift-J", I
probably should have said "quickMove, quickCopy, and quickJump".
If you do change the title of the ticket, feel free to make it:

quickMove, quickCopy, and quickJump misbehave when
viewing mails in a "conversation" window...

> (Plus that fact that you tend to submit multiple issues at once which 
> overwhelms my capacity)
>

Yeah, I'm definitely a little bursty.  I hope that's not a problem.
When I fall behind, I tend to start batching up tasks to try to
be more efficient.  Context switches slow me done a lot.

So, I tend to submit a bunch of accumulated bug tickets on the
same product all at once.  And tend to reply to a bunch of emails
from the same person all at once.  When I'm caught up on things
my batches get much smaller, sometimes just a single item.  I'm
not sure what to say about that, since I don't think I can change
it, except I'm sorry.  I hope it's not too overwhelming for you
when I send a burst.

> I think Thunderbird (or my code) somehow has problems determining the 
> original folder "we are in now".
>

Right.  I don't usually hit Cmd-Shift-O when the entire
conversation is in a single folder.  Then I see the messages
threaded into conversations anyhow.  I only use it when I've
already copied and/or moved some of the messages into
various folders for permanent storage while others of them
are still in my Inbox, or perhaps accidentally in Trash, or
only in Sent because my BCC copy hasn't yet arrived.

Once I see the entire conversation in a single window, with
each message showing a folder name in its Location column,
I then want to move/copy the various messages to the folders
I want them in.  Or sometimes jump to a different folder to
see what else is there.

Cmd-Shift-O is REALLY useful to me.  And would be even
better if quickMove, quickCopy and quickJump worked from
that view.  As I said, my current workaround is to right click
a message, choose "Open Message in Containing Folder" to
see it in a new tab, then use quickMove, quickCopy or
quickJump, then hit Cmd-W to close the new tab.  Clunky,
but it's the best I've found so far.


> I need to check what I am doing here, but generally it should get the 
> source folder(s) from the actual emails hightlighted. Except it does 
> this really STUPID assumption that the first email in the list gives 
> the folder (and that the other highlighted emails are in the same folder).
>
> At least that is my understanding of now, please correct me if I am 
> wrong...
>

Sounds likely.  In any case, the net effect is that the QF text
box comes up showing the last text string I typed into it.
And ignores any new chars I type.  The chars each appear
correctly as I type them, so the text box part is fine.  But
when I hit down arrow the menu shows matches for the
test I just got rid of.

For example, if the previous string was Fred and the new
string is Brita, it looks like this:
- http://bristle.com/Temp/QF_136.png

BTW, how do I conveniently store such images at GitHub to
be part of the ticket like you always do?  I like the way that
works because they are linked to by the emails I get from
GitHub, not embedded in the body of the message.  But they
are still displayed in-line in the body of the message.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by fredstluka** [comment] 2021-04-16 00:57
Axle,

Right.  I see the same in the error console with most, but
not all, of the same line numbers:

Uncaught TypeError: currentFolder is null quickfolders-util.js:1924:5
     allFoldersIterator 
chrome://quickfolders/content/quickfolders-util.js:1924
     allFoldersMatch chrome://quickfolders/content/quickfolders-util.js:2113
     findFolderName 
chrome://quickfolders/content/quickfolders-interface.js:4821
     initDelayed chrome://quickfolders/content/quickfolders.js:749

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by fredstluka** [comment] 2021-04-16 01:15
Axel,

Yeah, that sounds right.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by fredstluka** [comment] 2021-04-16 01:26
Axel,

Tried the new zip file.  Works perfectly.  Thanks!

As you said, the "Only show results from current mail
account" option does not work from a conversation view.
But does still work from regular mail folders.  That's
fine with me because I don't use that feature.  Instead,
I mark all but one of my accounts as to be excluded.

Frank, does that fix all of your related problems too?

If so, I think you can close the ticket, Axel.

Thanks!
--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-04-16 11:00
> Axel, Tried the new zip file.  Works perfectly.  Thanks! As you said, the "Only show results from current mail account" option does not work from a conversation view. But does still work from regular mail folders.  That's fine with me because I don't use that feature.  Instead, I mark all but one of my accounts as to be excluded. Frank, does that fix all of your related problems too? If so, I think you can close the ticket, Axel. Thanks! 

Thanks - I will close this issue once I officially release QuickFolders 5.5 so that people will see this one as active in the meantime and are able to test the [fix above](https://github.com/RealRaven2000/QuickFolders/issues/136#issuecomment-818661833) themselves. By the way you could have saved some time by visiting the github issue and reply from the bottom - rather than replying to every comment in chronological order.

There should be an option to get a copy of your own comments sent to you on github if you reply from here, which would fulfill your archivary needs... Otherwise (if you stick to replying from email) please snip out as much as you can (e.g. appelations / signatures and full on quoted threads are unnecessaryk, just clutter the issue pages and make them less accessible for others).

**Comment by fredstluka** [comment] 2021-04-16 12:23
Axel/Frank,

As Axel probably anticipated, I've now confirmed that this version
fixes the use of quickMove, quickCopy, and quickJump not only
from:
- Conversation view (Cmd-Shift-O)
but also from:
- Show search results as list view

Thanks, Axel!
--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by fredstluka** [comment] 2021-04-16 19:05
Axel,

Yeah, I have the GitHub option set to email me my own comments.

Yeah, I could have gone to GitHub to reply, but I still would have
had to read all the comments.  I did read the whole thread in
email before I started to reply.  But I replied to each message to
comment on what was said there.  And I could then delete, or
file away, or mark with star, each one I'd replied to.  At GitHub
there's no easy way to mark which comments I've dealt with and
which I haven't even read yet.  Since I get interrupted a lot, I never
know if I'm going to get all the way through something like that
long list of comments, or get interrupted first.  So, it's easier to
just do them one at time, like I do all of my emails.

At GitHub, you can't even nest comments under other comments,
so it all comes out as one long un-indented list of comments.
Bummer!  But most bug tracking systems seem to be like that.
I think even Jira doesn't support nested comments.

I generally prefer to work from email rather than directly at the
GitHub web site.  But, yeah, I could trim out some of the quoted
stuff when it's not relevant.

My .sig file shouldn't be a problem at GitHub, and same for
allowing Thunderbird to append a copy of the message I'm
replying to, because GitHub shows only the email without those
unless you click on the "..." button to see it all, right?

Like with this message.  The last line you should see at
GitHub is this one.  True?

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-04-16 19:19
> At GitHub, you can't even nest comments under other comments, so it all comes out as one long un-indented list of comments. Bummer!  But most bug tracking systems seem to be like that. I think even Jira doesn't support nested comments. 

> > let's test that

I just inserted the above by using two `>` , so it is possible with markdown

> I generally prefer to work from email rather than directly at the GitHub web site.  But, yeah, I could trim out some of the quoted stuff when it's not relevant. 

> My .sig file shouldn't be a problem at GitHub, and same for allowing Thunderbird to append a copy of the message I'm replying to, because GitHub shows only the email without those unless you click on the "..." button to see it all, right? Like with this message.  The last line you should see at GitHub is this one.  True?

yes, this is what I see:

![image](https://user-images.githubusercontent.com/6314674/115073618-81166400-9ef0-11eb-95ae-f7194e7e9357.png)

but I usually would go in (on the website) and delete all that to keep it really clean. Once I learned markdown I was quite happy because I don't really want all my signature and info and included thunderbird bitmap on here.

**Comment by fredstluka** [comment] 2021-04-16 20:33
Axel,

Oops!  Let me clarify...   I didn't mean multiple nested levels of
quoting within a single GitHub comments.  Yes, Markdown
supports that.

I mean multiple nested levels of GitHub comments attached to
a GitHub issue.  This entire email from me is one comment.
It's stored in the same linear list of comments attached to the
issue, right?  It's not displayed as a nested comment indented
relative to the comment I'm replying to, like you might see in
Facebook (only 2 levels of nesting supported) or an email
conversation thread in Thunderbird (many levels of nesting
supported).

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-04-18 20:31
Fixed in in 5.5 / 4.21.2 published today

**Closed by RealRaven2000** 2021-04-18 20:31 UTC
Labels: bug, regression Tb78

**Comment by RealRaven2000** [comment] 2021-04-27 10:55
5.5.1 published today which implements this for Thunderbird 78 users.

**Comment by fredstluka** [comment] 2021-04-28 00:23
Axel,

> 5.5.1 published today which implements this for Thunderbird 78 users.

This version didn't install itself automatically or prompt me or
anything.  When I saw this email, I went manually to the TB
Add-ons manager and told it to check for updates.  I haven't
had to do that in the past, but maybe I just didn't wait long
enough?  Maybe if I'd restarted TB?

Then the splash screen appeared, saying it was updated to 5.5.1.
The splash screen showed me a button to see "What's New" in
more details.  That took me to:
- https://quickfolders.org/version.html?user=pro#5.5.1
where I saw:
     "Changed folder tree shortcut from F7 to F9 (consistent with
     Thunderbird 68). Push F0 to make the folder tree visible or
     quickly hide it."

Questions:

1. How do I get the splash screen to re-appear?  I clicked
     "What's New" before I finished reading it.

2. Is the F0 above a typo?  Should be F9 perhaps?

3. Is there an alternate key to show/hide the folder tree?
     Sounds like a useful feature, but F9 is already used for
     another purpose Mac-wide, and I'd rather not change
     that.  F7 would be fine.

Thanks!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-04-28 09:25
> Axel,
> 5.5.1 published today which implements this for Thunderbird 78 users.
> > This version didn't install itself automatically or prompt me or anything.  When I saw this email, I went manually to the TB Add-ons manager and told it to check for updates.  I haven't had to do that in the past, but maybe I just didn't wait long enough?

It should auto-update (I just tested it by installing 5.5 and then restarted and ran "check for updates" and it updated to 5.1 - it is possible that you installed a preview version which was tagged as 5.6preXX before I decided to publish the patch and the mechanism will never downgrade your version.

> Then the splash screen appeared, saying it was updated to 5.5.1. The splash screen showed me a button to see "What's New" in more details.  That took me to: - https://quickfolders.org/version.html?user=pro#5.5.1 where I saw:     "Changed folder tree shortcut from F7 to F9 (consistent with     Thunderbird 68). Push F0 to make the folder tree visible or     quickly hide it." Questions: 1. How do I get the splash screen to re-appear?  I clicked     "What's New" before I finished reading it. 2. Is the F0 above a typo?  

Typo! I fixed that, thanks for noticing.

Should be F9 perhaps? 

> 3. Is there an alternate key to show/hide the folder tree?     Sounds like a useful feature, but F9 is already used for     another purpose Mac-wide, and I'd rather not change that.  F7 would be fine. Thanks!

I saw that it had been changed at some stage to F7 and I had forgotten about it so I changed it back. Obviously I hadn't documented that properly, but I must have made the change at some stage for my Mac users. I think the best way forward would be to make it configurable - that would also be a step forward to increase visibility for the feature. Feel free to open a new issue for that one in case I forget it!

**Comment by fredstluka** [comment] 2021-04-28 11:53
Axel,

> Feel free to open a new issue for that one in case I forget it!
OK.  I added #149.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------
