### ISSUE TITLE
Dragging mail to quickMove Button leaves folder popup menu hanging on first tab (Tb 115)

### ISSUE THREAD

**Issue by w-ponds** [RealRaven2000/QuickFolders#410] opened 2023-09-29 18:31 UTC
After upgrading to TB115 the QuickMove button now behaves differently than before. When dragging e-mails to the QuickMove button it will pull up the Inbox tab as it passes over it. Once the Inbox tab is opened it will not close and remains in focus even after dropping the e-mail onto the QuickMove button. If I begin typing the folder name for the QuickMove it will instead try to pull up top level folders under the Inbox tab. I have to click in the QuickMove typing box in order to be able to type there. 
This may be related to the above but if I drag over any tabs it will expand those tabs and leave them expanded until I drop the message. I'm not sure but maybe this is due to an aggressive hover time? The tabs expand almost instantly and I'm fairly certain there used to be a slight pause before expansion.

**Comment by RealRaven2000** [comment] 2023-09-29 18:53
Thanks for reporting, I will look into this! Yeah hanging popup menus are annoying. Not sure that I want to do delays on the menus though, but they should definitely close as soon as we leave the button / tab. I will look into the button's dragExit event for this, but I think this is also triggered when the user pulls down into the actual menu - obviously we don't want to close the menu in that case!

**Comment by RealRaven2000** [comment] 2023-09-29 18:54
Actually I can probably do you one better. I can use the `dragEnter` event on the quickMove button (or the whole area there) and make sure to close all menus in that case...

**Comment by RealRaven2000** [comment] 2023-11-19 20:31
Marking as duplicate of #428 (there is a fixed test version there)

**Comment by w-ponds** [comment] 2023-11-20 03:42
I can confirm that the issue seems to be fixed for all of the regular tabs. However, I still have an issue when dragging to the quickMove button. It seems there is an overlap of the focus zones for the quickMove button and the next tab over (Inbox in my case). This causes both the Inbox tab and quickMove box to be in focus at the same time. However, if I begin typing after dropping onto the quickMove button and after the quickMove text box pops up it will actually select subfolders of the Inbox matching the letters I'm typing instead. The Inbox tab still retains focus even though the quickMove text box is open. A workaround is to move the mouse a little further to the left and away from the Inbox tab so that it will close before dropping. I am nearly off of the quickMove button and at the edge of my window by the time the Inbox tab closes. One solution might be to add some space between the quickMove button and the first tab to the right. I would prefer this anyway as it would make it faster to drag and drop onto the button.

**Comment by RealRaven2000** [comment] 2023-11-20 06:27
that's strange behaviour - the dragleave event should fire as soon as the mouse cursor is dragged outside of the tab - I haven't seen  this behaviour but I have the recent folder tab visible.  can you enablej it to see whether it still happens then?

**Comment by RealRaven2000** [comment] 2023-11-20 11:00
Ok, I could reproduce this after removing the Recent folders tab, interestingly I get 2 different behaviors
1 - when dragging directly to quickMove, the popup is not closed (I haven't tested the keysatroke behavior yet but the root is probably that the menu it not closed.
2 - if I drag to the left into an empty area of the toolbar and then drag down to quickMove then the menu is closed:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/624d186c-2e4b-45a1-acd0-260a68c7f5ef)

So there is a problem that the event is not fired for some reason maybe when going straight from one toolbar button to another (without hitting a bit of the toolbar background first). My guess is only entering the background element (the toolbar) somehow triggers the `dragLeave` event for the button. I can log this using the debug.dnd.detail but that will flood the error console with messages so I will make it appear also for debug.dnd and do some testing to make a working theory...

**Comment by RealRaven2000** [comment] 2023-11-20 12:35
Looks like absolutely none of my `dragExit` or `dragLeave` events actually fire. So I have to make sure to remove the popup when any of the buttons on the toolbar area to the left of the QuickFolders tab get a `dragEnter` event. I think this whole item is significant enough to get an extra mention / issue for the change log of the next release. 

Here is a test version that seems to work for me (menus are still hanging if you drag the email back into the thread pane, which I cannot prevent right now)

[QuickFolders-mx-6.3.1pre31.zip](https://github.com/RealRaven2000/QuickFolders/files/13414511/QuickFolders-mx-6.3.1pre31.zip)

----

To test the version above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by w-ponds** [comment] 2023-11-20 14:56
I just tried the 6.3.1pre31 and it seems to be working as it should now. Good job! The issue with hanging menus when you drag back into the thread pane is a lot less of a nuisance for me. Usually when I am dragging I'm ready to file so I don't drag back into the thread pane.

**Comment by RealRaven2000** [comment] 2023-12-04 17:09
Fixed in 6.4 released on 04/12/2023

**Closed as completed by RealRaven2000** 2023-12-04 17:09 UTC
Labels: bug, ESR 115
