### ISSUE TITLE
Move mail to folder using CTRL+Number not working

### ISSUE THREAD

**Issue by herve-debar** [RealRaven2000/QuickFolders#493] opened 2024-08-19 12:26 UTC
Hi, I used to be able to move a selected message to a QuickFolder folder by <Control>+<Number>. I initially did it with ALT (Command) on MAC but it stopped working a while ago. This doesn't seem to work anymore.

**Comment by RealRaven2000** [comment] 2024-08-19 13:03
> Hi, I used to be able to move a selected message to a QuickFolder folder by +. I initially did it with ALT (Command) on MAC but it stopped working a while ago. This doesn't seem to work anymore.

is something missing here? Maybe `CTRL`+`Number` or something? If you can please respond directly from the Github website, replies by Email get stuff wrong, and the editor here is friendly (support Markdown).

Also take a look at this:

![image](https://github.com/user-attachments/assets/598dd6dd-0910-43e7-bbe1-90ea757f90cc)

it links to an instruction on #387 that is specific to Thunderbird 115 (and later)

**Comment by herve-debar** [comment] 2024-08-19 13:31
Here are a few additions.
I have Thunderbird 128.1.0esr on MacOS Sonoma version 14.6.1.
On the above I have the "use Ctrl instead of Alt" checked.
If I understand correctly your comment to #387 I must install and configure tbkeys-lite ? 
However, the configuration you propose for tbkeys-lite touches "ALT", not "CTRL". Should it not work with CTRL if the box is checked ? 
Best.

**Comment by RealRaven2000** [comment] 2024-08-19 13:55
> Here are a few additions. I have Thunderbird 128.1.0esr on MacOS Sonoma version 14.6.1. On the above I have the "use Ctrl instead of Alt" checked. If I understand correctly your comment to #387 I must install and configure tbkeys-lite ? 

that's correct. because otherwise Thunderbird gobbles up these keystrokes.

> However, the configuration you propose for tbkeys-lite touches "ALT", not "CTRL". Should it not work with CTRL if the box is checked ? Best.

I am not a specialist on MacOS (only Mac device I currently have is an iPad) but you can try ALT (= Command) without the checkbox or CTRL with the checkbox. Both sets of shortcuts are heavily occupied by Thunderbird, by default.

**Comment by RealRaven2000** [comment] 2024-08-19 14:11
looks like we found a regression. the ctrl+Number shortcut was filtered for `keyup` events only but the last fix for Tb128 only looks at `keydown` events.
Here is a quickfix:

[QuickFolders-mx-6.7.1pre8.zip](https://github.com/user-attachments/files/16661368/QuickFolders-mx-6.7.1pre8.zip)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by herve-debar** [comment] 2024-08-19 14:57
Works ! 
And it's good because the tbkeys-lite addon default config seems to break another shortcut I frequently use !
Thanks !

**Comment by RealRaven2000** [comment] 2024-08-19 17:23
nice one - tbkeys lite comes with a lot of presets that you may not agree with so I would delete the lines that don't apply. I will close this issue when I publish a patched version of QuickFolders (shortly)

**Comment by RealRaven2000** [comment] 2024-08-20 10:04
By the way just for the record - this issue was caused by working on #491

**Comment by SvJo007** [comment] 2024-09-17 19:08
Will there perhaps soon be an update that fixes the problem described?
I can't get the zip file mentioned above to install. TB would like an xpi file ... :-(

**Comment by RealRaven2000** [comment] 2024-09-17 19:23
> Will there perhaps soon be an update that fixes the problem described? I can't get the zip file mentioned above to install. TB would like an xpi file ... :-(

it should work by pulling it into the Add-ons Manager, but you can always rename it to fileName.xpi instead. factually that is the same format.

**Comment by SvJo007** [comment] 2024-09-20 09:18
Thanks for the help. It is now working perfectly again!
And a big compliment. This is the TB extension I use the most. I immediately extended my pro license.

**Comment by RealRaven2000** [comment] 2024-11-25 14:10
Fixed in 6.8 - Published 25/11/2024

**Closed as completed by RealRaven2000** 2024-11-25 14:10 UTC
Labels: ESR 128, regression
