### ISSUE TITLE
quickMove - with duplicated folder name, repeat to last folder may end up in wrong path 

### ISSUE THREAD

**Issue by jaysmithgit** [RealRaven2000/QuickFolders#241] opened 2022-03-07 20:21 UTC
I have confirmed that the 5.5.2 PRO bug I found today **also exists** in 5.8.3 PRO.  (I have upgraded to 5.8.3.  I am on TB 78.7.1.)

This is a little complicated.  Please bear with me.

1) This bug apparently can only exist in Pro because only in Pro it is possible to move messages by starting with a keystroke. 

2) I have assigned "s" (save) for my use, but I think the default may be "m".  I mention this in case the bug is related to me not using the original default keystroke for this function.

3) I am able to repeat this problem.

4) Necessary folders environment to have this problem: Two or more folders with the same TERMINAL folder name, such as "alerts"...

../../../bank-one/alerts
../../../insurance-one/alerts
../../../company-two/alerts
...... etc.

5) First, type "s" (for ME to *move* mail messages, could be another letter as configured), followed by "alerts". That results in showing a folder list showing the folder paths I have listed above. Then use the keyboard down-arrow key to navigate to the SECOND OR FURTHER folder (NOT the first one -- the first one does not have a bug).  Type <Enter> to move message to that folder: ../../../insurance-one/alerts

6) Then ... because I found another message that I want to move to the same folder as before ... type "s" (for ME to *move* mail messages, could be another letter as configured).... That results in showing the ***SINGLE WORD*** "alerts" in the recent-folders BOX (the recent-folders BOX does not show anything more than that single word unless you type a down-arrow; then it shows the list of the paths that contain "alerts").  (The bug....) type <Enter> to move message to that "alerts" folder.

7) You may disagree with me, but my expectations is that the word "alerts" in the recent-folder BOX should represent the **folder** into which I last moved a message.  At least that is what I thought for many months. in this case my assumption was that would represent ../../../insurance-one/alerts.  However, **instead,** it represents the **FIRST** path in the list (i.e. ../../../bank-one/alerts).  It moves the message into that **FIRST** path on the list, rather than the expected path (rather than the folder into which I moved the message the last time).

8) Back on 5.5.2, it was NOT possible to down-arrow in step 7.  However, in 5.8.3 (or sometime since 5.5.2) it is now possible to down-arrow in step 7 (I think this corrected a bug report I filed).  Thus the user can in 5.8.3 down arrow to the correct full path.  But... if the user has assumed that "alerts" represents the folder that they moved messages to last time, they will be severely disappointed to eventually discover their messages are in folders other than what they expected.  (Today I discovered several hundred such incorrectly filed messages, but it was easy to clean up.)

So, in 5.8.3 by using down-arrow, there is no problem.  However, if the user just sees "alerts" and assumes that it is the desired "alerts" folder, and types <enter>, there is a problem.

I hope this makes sense.

**Comment by RealRaven2000** [comment] 2022-03-07 22:18
> 6. Then ... because I found another message that I want to move to the same folder as before ... type "s" (for ME to _move_ mail messages, could be another letter as configured).... That results in showing the _**SINGLE WORD**_ "alerts" in the recent-folders BOX (the recent-folders BOX does not show anything more than that single word unless you type a down-arrow; then it shows the list of the paths that contain "alerts").  (The bug....) type  to move message to that "alerts" folder.
> 7. You may disagree with me, but my expectations is that the word "alerts" in the recent-folder BOX should represent the folder into which I last moved a message. At least that is what I thought for many months. in this case my assumption was that would represent ../../../insurance-one/alerts. However, instead, it represents the FIRST path in the list (i.e. ../../../bank-one/alerts). It moves the message into that FIRST path on the list, rather than the expected path (rather than the folder into which I moved the message the last time).

I agree - the text "alerts" was intended as a placeholder for the last successful quickJump / quickMove operation. I think it might (should?) have been displayed with the parent name as well if it wasn't unique in the original mail move / jump operation. I need to investigate in detail why it doesn't work as intended in your case. May I suggest that we change your complicated title to "quickMove - with duplicated folder name, repeat to last folder may end up in wrong path "

**Comment by RealRaven2000** [comment] 2022-03-07 22:28
You can check what QuickFolders stores (I think in the case of entering parentname/childname it works) by enabling the debug switch quickMove. Open QuickFolders options, advanced settings and enable debug. Then right-click debug and enable:

![image](https://user-images.githubusercontent.com/6314674/157128229-884bd5b0-8250-491d-a09f-766c863672dc.png)

`extensions.quickfolders.debug.quickMove = true`

this will add the detail on what is stored when you enter a new destination to move mails to. It should really store the complete folder path  in a second part. The problem is that if you only enter the destination folder name (and no parent) during the search it probably doesn't "know" that this isn't unique and doesn't store more detail.

**Comment by jaysmithgit** [comment] 2022-03-07 23:04
1) I have turned on `extensions.quickfolders.debug.quickMove = true`.  But then what?  How do I then see the stored information to which you refer?

2) ...
>  The problem is that if you only enter the destination folder name (and no parent) during the search it probably doesn't "know" that this isn't unique and doesn't store more detail.

But should it not store the complete path regardless?  Not just the part that was last searched?

**Comment by jaysmithgit** [comment] 2022-03-07 23:07
> May I suggest that we change your complicated title to "quickMove - with duplicated folder name, repeat to last folder may end up in wrong path "

I have made the change. You are always welcome to change the "subject" to whatever you feel is most appropriate. I know my terminology may not be correct for the situation.

**Comment by jaysmithgit** [comment] 2022-03-07 23:29
I finally figured out that the debug information is under TB's Tools _> Developer Tools -> Error Console. I cleared the history and then did a move message (by typing MY "s" followed by "alerts" and selecting a specific path & folder).  I am emailing the result directly to you.

In only one place in all the messages is the full path mentioned.  Otherwise, all other mentions are of the search string ("alerts").

**Comment by RealRaven2000** [comment] 2022-03-08 09:33
> > The problem is that if you only enter the destination folder name (and no parent) during the search it probably doesn't "know" that this isn't unique and doesn't store more detail.
> 
> But should it not store the complete path regardless? Not just the part that was last searched?

Yes I think it probably should. Here is the reason why I didn't catch this:

- when you enter a search term and the desired folder is on top of the suggestions, just hitting Enter will select the top item and jump to the folder.
- for this reason (and since I don't like going through long menus with the cursor keys) I had developed a habit of entering the [partial] parent name when I searched for an ambiguous folder name. So in your case I probably would have entered "in/ale" to get the folder "insurance-one/alerts" to show up on top. Once I hit enter, then the (unambiguous) string "insurance-one/alerts" would be stored in the "last successful quickMove" string. I didn't store the complete path because I didn't want a complete path to show up in the search field.

To remedy this problem I obviously need to store both (the text you entered and the full path). But it would still be nice if the algorithm could determine whether the auto-filled name was actually unambiguous and (if not) add the necessary parent folder in the field. This is actually technically difficult as it should only show the minimal amount of parents necessary. So I would also have to think of an algorithm to do this

Let's consider we have 3 folders labelled "alerts":

../../../bank-one/alerts
../../../insurance-one/divisionX/alerts
../../../company-two/divisionX/alerts

What would be a unique string for the second item? Since both have a direct parent divisionX this is useless as a distinguishing component. Of course one could show "insurance-one/divisionX/alerts" but the path is very log and hard to read.

One way to find he correct path in this example would be by typing "**insurance-one>alerts**" (or short "in>alerts") so that would be a possibility to store as last successful search. But that would obviously not be unambiguous anymore once we create another folder

../../../insurance-one/divisionA/alerts

In any case, the full path of the last successful  quickMove / quickJump operation should be stored. Maybe even the last 5 or 10 if I can think of a simple and useful way of adding them to the menu. The easiest might be using the arrow down key when nothing has been typed yet. This could show the last 10 quickJump locations if you used the shortcut for quickJump and the lat 10 quickMove locations in the case of quickMove. If I implement something like this I will likely create a new github issue to track it. 

For the purposes of _this_ issue #241 I will just store the full path of the last operation as you suggested, and store the entered search string (for displaying in the text box) separately.

**Comment by jaysmithgit** [comment] 2022-03-09 18:44
> In any case, the full path of the last successful quickMove / quickJump operation should be stored. Maybe even the last 5 or 10 if I can think of a simple and useful way of adding them to the menu. The easiest might be using the arrow down key when nothing has been typed yet. This could show the last 10 quickJump locations if you used the shortcut for quickJump and the lat 10 quickMove locations in the case of quickMove. If I implement something like this I will likely create a new github issue to track it.

I can appreciate the difficulties involved. 

I agree that being able to use the down-arrow key after the initial keystroke (i.e. in my case, "s" for save / quickMove), would be great. 

However, since you pointed out to me that (in my case) "s=" starts the quickMove process and then makes visible the recent-list, I **can** use the down-arrow to select a folder once the recent list is visible and type<Enter> to quickMove the email message to the selected destination folder.   

In my opinion, that method could be enough of a solution.  And it also deals with wider range of uses, such a doing quickMove into various different folders (i.e. move to 1, 2, 3, 1, 2, 3, 3, 3, 1, 1, 2, 3, 4, etc.)

**However, in order for that to work, the bug discussed in Issue #240 must first be fixed.**  (The "s = <Enter>" results in a quickJump instead of a quickMove.)

> > BUT... it is **not** working as expected. Instead the ["s", "=", and navigating in the recent list, "Enter" to select an item in the recent list} is NOT moving the email message. Instead it is going [jumping] to and opening the target folder.
> > Do you see the same behavior or it is just me?
> 
> Yes - I think this may be a bug. It should definitely move the mail. The `=` shortcut was never officially documented because of the developer of nostalgy++ complaining that too many features of his Add-on were demanded by users from QuickFolders. So on top of integrating Recent folders with quickMove / quickJump in ajn intuitive, / easy way I also have to worry about taking away users from his base which is not something I want.

**Comment by RealRaven2000** [comment] 2022-03-10 15:28
Can you test this version:

[QuickFolders-mx-5.9pre28.zip](https://github.com/RealRaven2000/QuickFolders/files/8224657/QuickFolders-mx-5.9pre28.zip)

If you hit Enter (only when the menu is NOT shown) then the last location should be selected. Hast to be initialized once (explicit jump into a folder) and then should work forever. If you type the "down" arrow instead it should open the results and Enter would default to the top item in the list instead. If you type anything in the box then the menu will show and Enter always selects the top item, as before.

**Comment by jaysmithgit** [comment] 2022-03-11 21:47
Now using [QuickFolders-mx-5.9pre33.zip] ... (I never got to pre28 before you made pre33)...

My response on this is slightly 'mixed', but I think we have a winner!  Yeah!

On one hand it is now **working** and putting the moved messages into the intended folder. 

On the other hand, I thought at one point (perhaps in the #240 thread?) I thought I understood you to be saying that you would (or might), when doing a repeated quickMove, make the information in the search box say more of the path, not just the terminal folder name (when the original search typing by the user was only the terminal folder name).

So, using our previous examples, the search box still says "alerts" under version 5.9pre33.

However, it **does correctly quickMove into the last-moved-into folder** and *not* just (potentially incorrectly) into the top folder in the list.

Whether or not you want more of the path name visible in the search box is above my pay grade.  It **IS** working well for me now -- the quickMove is moving emails to the expected folder.

(If it is important to the particular user to see the other folders in the search result list for "alerts", the user **CAN** down-arrow and then the list becomes visible and the user, can, if the users wishes to do so, select any folder in that list for quickMove into.)

Thank you for your excellent dedication to this work.

**Comment by fanis** [comment] 2022-03-18 12:55
I came here searching as I also have same folder names in differently named subfolders and subsequent go/save/copy just selects the first in the list.

I tried QuickFolders-mx-5.9pre33.zip and it works wonderfully, nice to see such commitment and professionalism yet again @RealRaven2000 , and great job reporting and working on it @jaysmithgit .

**Comment by jaysmithgit** [comment] 2022-03-18 14:23
> I came here searching as I also have same folder names in differently named subfolders and subsequent go/save/copy just selects the first in the list. I tried QuickFolders-mx-5.9pre33.zip and it works wonderfully, nice to see such commitment and professionalism yet again @RealRaven2000 , and great job reporting and working on it @jaysmithgit .

Thanks @fanis -- I am just an "ordinary" user, but I believe in doing all I can to assist developers in improving their products. Too many people in our world just assume "somebody else will report it or fix it."   I am glad that my efforts helped to solve the same problem you were having.  The developer of QF is both very talented and very dedicated -- it is a pleasure to use such a useful add-on.

**Comment by RealRaven2000** [comment] 2022-04-02 10:39
Fixed in 5.9, released on 30/03/2022

**Closed by RealRaven2000** 2022-04-02 10:39 UTC
