### ISSUE TITLE
Dragging an email to a tab can be thwarted by another tab opening its sub-folders

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#357] opened 2023-05-07 17:19 UTC
Unless I make some mistake (and I am sorry if I do!) the user has no option to change the amount of time that, when spent with the point over a tab, triggers the opening of a menu showing the relevant subfolders. I should like to increase that quantity of time. For, at present, sometimes my dragging of an email to a tab is interrupted, because the path between the email and tab takes in another tab, and that other tab's subfolders spring open.

QuickFolders 5.16.1
Thunderbird 102.10.1
Windows 10

**Comment by RealRaven2000** [comment] 2023-05-07 18:06
If you drag from bottom to top or from left to right it should not matter. I don't really want to add a delay here as it will definitely slow down people who use dragging into subfolders often.

**Comment by LinuxOnTheDesktop** [comment] 2023-05-07 20:18
@RealRaven2000: thanks.

> If you drag from bottom to top or from left to right it should not matter. 

I do not understand. Are you suggesting that I must (remember to) drag _around_ the tab the opens the submenu?

> I don't really want to add a delay here as it will definitely slow down people who use dragging into subfolders often.

I was angling for a facility for the user to be able to customise the delay.

**Comment by RealRaven2000** [comment] 2023-05-07 20:32
> @RealRaven2000: thanks.
> 
> > If you drag from bottom to top or from left to right it should not matter.
> 
> I do not understand. Are you suggesting that I must (remember to) drag _around_ the tab the opens the submenu?

no not around, but your emails are below the tabs, so you would be dragging them up, right?

A menu can only cover another menu that is further _down_. If you drag up you will see the menu from the bottom tab, but shortly after the menu from the tab on top (which may be your real target). you only would be stopped from hitting a menu if you "overshoot" and drag up to far and then tries to go down again.

**Comment by RealRaven2000** [comment] 2023-05-07 20:36
example - I am dragging an email to the top folder "Hotmail":

![image](https://user-images.githubusercontent.com/6314674/236701341-db58352e-e0ef-4a65-afab-901db539c55b.png)

if I want to to the next folder to the right (indigo) i can drag right and it will close the other submenu automatically:

![image](https://user-images.githubusercontent.com/6314674/236701382-2459da11-e3c0-445e-bc02-c43a7c503548.png)

- so I cannot see how one is covering the other? the only way this would happen if you were trying to go from the top row down to the bottom row. But the emails are usually underneath the QuickFolders toolbar. Could you provide a video or screenshots with an example?

**Comment by LinuxOnTheDesktop** [comment] 2023-05-07 20:55
Thank you for your work. Here is a video that shows two things:

1) how the submenu from one tab (namely, my 'products' tab) can block access to some other tab(s) to which it is adjacent (namely, my 'GiffGaff' and 'Tutoring' tabs);
2) how sometimes a submenu from one tab ends up being displayed at the same time as a submenu from another tab.


EDIT: video removed.

**Comment by RealRaven2000** [comment] 2023-05-07 21:20
Ok, the problem here is that some of the menus  have too many items and fill the whole screen vertically. I generally avoid that here, but I also think it is kind of bad behavior for a menu to do that (fill the screen in both directions). not quite sure what to do about that let me think on it.

**Comment by LinuxOnTheDesktop** [comment] 2023-05-07 21:22
Right. Thank. I'm going to delete the video in my earlier post (for privacy).

**Comment by RealRaven2000** [comment] 2023-11-19 20:46
Marking this as a duplicate of #428 (there is a test version there)

**Closed as completed by RealRaven2000** 2023-11-19 20:46 UTC
