### ISSUE TITLE
Thunderbird 91: move Folders in quickMove fails

### ISSUE THREAD

**Issue by staki1966** [RealRaven2000/QuickFolders#211] opened 2021-10-13 08:24 UTC
I have been using QuickFolders for quite some time. Recently I've been running TB78, but a couple of days ago I upgraded to 91.2.0. Since then, whenever I try to move folders, either by dragging them to the toolbar, or by Shift-M shortcut, the error "ReferenceError: toXPCOMArray is not defined".

TB error console shows

`
Exception in movefolder
toXPCOMArray is not defined
`

it points to the following line in source:

`
        let cs = Cc["@mozilla.org/messenger/messagecopyservice;1"].getService(Ci.nsIMsgCopyService),
            array = toXPCOMArray(folders, Ci.nsIMutableArray); // Tb 78
`

**Comment by RealRaven2000** [comment] 2021-10-13 09:51
Thanks for raising this - this is definitely a regression caused by Thunderbird 92. They removed the already deprecated `toXPCOMArray` (which I call unnecessary for an array conversion) but also they also dropped the array-based function `MailServices.copy.copyFolders` (which still existed in earlier versions such as Tb 88) which is now replaced with the singular function `MailServices.copy.copyFolder`.

Below is a test version with a quick fix:
[QuickFolders-mx-5.8pre42.zip](https://github.com/RealRaven2000/QuickFolders/files/7337006/QuickFolders-mx-5.8pre42.zip)

To install this, download the zip file then drag it into Thunderbird Add-ons Manager. Please leave the issue open even if it solves the problem, I am closing all related bugs when I release the next official QuickFolders.

**Closed as completed** 2021-10-20 21:48 UTC
Labels: bug, regression Tb91
