### ISSUE TITLE
Current Folder Toolbar display - text is always black

### ISSUE THREAD

**Issue by Vacoas** [RealRaven2000/QuickFolders#81] opened 2020-11-30 13:27 UTC
Hi,
I am currently using Thunderbird 78.5.0 and QuickFolders Pro 5.0.
In the main toolbar, the font used to display the tab varies depending on the tab colour (e.g. White for dark blue, black for yellow).

![image](https://user-images.githubusercontent.com/45902444/100615239-9c088300-3317-11eb-8f07-ed3156bb1a86.png)

The same does not apply to the Current Folder toolbar. The tab name is always in black, making it difficult to read in some cases.

![image](https://user-images.githubusercontent.com/45902444/100615319-b93d5180-3317-11eb-975c-c39fc42b22b1.png)
![image](https://user-images.githubusercontent.com/45902444/100615351-c5291380-3317-11eb-9c09-8e3d59749de7.png)
![image](https://user-images.githubusercontent.com/45902444/100615421-de31c480-3317-11eb-86de-e71b855a2a55.png)

Regards, 
MP

**Comment by RealRaven2000** [comment] 2020-11-30 16:57
I did some testing with dark themes on Tb68 vs 78. apparently the selector for the button is not specific enough. Please try out this version:

[QuickFolders-wx-5.1pre9.zip](https://github.com/RealRaven2000/QuickFolders/files/5617381/QuickFolders-wx-5.1pre9.zip)

To install, download the zip file and then drag into Add-ons Manager!

**Comment by RealRaven2000** [comment] 2020-11-30 17:04
I added an additional selector for label and icon on the "hovered" state, as well:

[Uploading QuickFolders-wx-5.1pre10.zip…]()

To install, download the zip file and then drag into Add-ons Manager!

**Comment by Vacoas** [comment] 2020-12-02 10:09
Just tested 5.1pre24. 
Folders for which there is NO tab are displayed correctly in the current folder toolbar :
![image](https://user-images.githubusercontent.com/45902444/100857513-0a228680-348d-11eb-9cc7-784c2edb478f.png)
Folders for which there IS a tab are not correctly displayed :
![image](https://user-images.githubusercontent.com/45902444/100857682-4950d780-348d-11eb-8ace-552fc8f6055b.png)

I am also running into a problem installing the version which seems to be Thunderbird-related and I had to copy the 'chrome' folder and others manually. More about that below.

**Comment by RealRaven2000** [comment] 2020-12-02 10:24
> Just tested 5.1pre24.
> Folders for which there IS a tab are not correctly displayed :
> ![image](https://user-images.githubusercontent.com/45902444/100857682-4950d780-348d-11eb-8ace-552fc8f6055b.png)
> 

I can't reproduce this [coloring works always even if tabs of the current folder exist] - did you restart Thunderbird just in case old CSS rules were "hanging around"? What color settings have you set for "Uncolored tabs" - it would be best if you could post a screenshot of your color settings (bling my tabs) in the QuickFolders options dialog.

As example, here are my settings for testing with a dark theme:
![image](https://user-images.githubusercontent.com/6314674/100860436-6afb9000-3488-11eb-9f17-b444796b57e4.png)

please leave ths issue open until I officially release 5.1 on atn.

**Comment by Vacoas** [comment] 2020-12-02 10:32
![image](https://user-images.githubusercontent.com/45902444/100861106-a8b0e680-3491-11eb-854c-cbb540d57dfa.png)
I did restart Thunderbird every time I loaded something new.

**Comment by RealRaven2000** [comment] 2020-12-02 14:30
I just tried your color settings on my system still can't reproduce - I believe it may be theme colors specific to your Operating System - which one are you on?

You could inspect the current folder element via tools / developer tools / developer toolbox and the inspector:
![image](https://user-images.githubusercontent.com/6314674/100885234-54fec700-34aa-11eb-8ba4-6bbe062715ed.png)

once you activate the element picker, click on the current folder panel:
![image](https://user-images.githubusercontent.com/6314674/100885338-7069d200-34aa-11eb-9ded-98785dbbdd58.png)

Expand the `toolbarbutton` element in the left hand pane and click on `label`:
![image](https://user-images.githubusercontent.com/6314674/100885482-998a6280-34aa-11eb-9829-a622d019146b.png)

on the right hand side select "Computed" (Styles) and expand the `color` rule:
![image](https://user-images.githubusercontent.com/6314674/100885602-c2125c80-34aa-11eb-840f-5ffe4605f0dc.png)

you should see the "winning" rule / selector on top. just paste a screenshot of this set of rules and we can go forward. It is interesting to know the exact selector with the black color, the css file name and line number.

**Comment by Vacoas** [comment] 2020-12-03 17:55
Hi,
    
    I am running Windows 10 20H2 with all the most recent updates
    19042.662.
    
    To perform the testing I removed all extensions except QuickFolders
    to make sure they do not interfere. Especially, the DeepDark
    extension that uses specific files in a chrome directory. 
    
    The installation of 5.1pre24 went fine.
    
    I first tested the Current Folder Toolbar for a folder which does
    not have a tab
    
    
    
    
    
    
    
    
    
    Then I did the same thing with a folder that has a tab 
    
    
    
    
    I find the toolbarbutton-text entry for 'Atlantico' twice :
    
    
    
    
    
    
    
    Regards,
    
    Maurice
    
    Le 02/12/2020 à 15:30, RealRaven2000 a
      écrit :
    
    
      
      I just tried your color settings on my system still can't
        reproduce - I believe it may be theme colors specific to your
        Operating System - which one are you on?
      You could inspect the current folder element via tools /
        developer tools / developer toolbox and the inspector:
        
      once you activate the element picker, click on the current
        folder panel:
        
      Expand the toolbarbutton element in the left hand
        pane and click on label:
        
      on the right hand side select "Computed" (Styles) and expand
        the color rule:
        
      you should see the "winning" rule / selector on top. just paste
        a screenshot of this set of rules and we can go forward. It is
        interesting to know the exact selector with the black color, the
        css file name and line number.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-737265180",
"url": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-737265180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Vacoas** [comment] 2020-12-05 13:25
Here are the steps I performed.
Starting Thunderbird with a current folder such as 'Contrepoints'.
Selecting 'Figaro' in the folder pane.
This seems to generate two actions as I have 2 entries for 'toolbarbutton-text' and 'Figaro'.
The first entry has the right color for the text: rgb(220,235,245).
The second entry comes back with rgb(0,0,0) which seems to overwrite the previous entry.

![Figaro 01_cr](https://user-images.githubusercontent.com/45902444/101244231-76a7ba80-3705-11eb-9f63-52a52f1ca902.jpg)
![Figaro 02_cr](https://user-images.githubusercontent.com/45902444/101244234-7f988c00-3705-11eb-9ebf-4a8e311aad16.jpg)
![Figaro 03_cr](https://user-images.githubusercontent.com/45902444/101244242-8b844e00-3705-11eb-9c27-a6bbd7f22368.jpg)
![Figaro 04_cr](https://user-images.githubusercontent.com/45902444/101244252-97701000-3705-11eb-8e49-efa0fdfebab5.jpg)

**Comment by RealRaven2000** [comment] 2020-12-05 13:41
> Hi, I am running Windows 10 20H2 with all the most recent updates 19042.662. To perform the testing I removed all extensions except QuickFolders to make sure they do not interfere. Especially, the DeepDark extension that uses specific files in a chrome directory. The installation of 5.1pre24 went fine. I first tested the Current Folder Toolbar for a folder which does not have a tab Then I did the same thing with a folder that has a tab I find the toolbarbutton-text entry for 'Atlantico' twice : Regards, Maurice Le 02/12/2020 à 15:30, RealRaven2000 a écrit :
> […](#)
> I just tried your color settings on my system still can't reproduce - I believe it may be theme colors specific to your Operating System - which one are you on? You could inspect the current folder element via tools / developer tools / developer toolbox and the inspector: once you activate the element picker, click on the current folder panel: Expand the toolbarbutton element in the left hand pane and click on label: on the right hand side select "Computed" (Styles) and expand the color rule: you should see the "winning" rule / selector on top. just paste a screenshot of this set of rules and we can go forward. It is interesting to know the exact selector with the black color, the css file name and line number.

If you want to send screenshot, please do it from github directly. Directly replied mails are very hard to read. (I edited your first post to make it a little easier, but screens were missing)

**Comment by RealRaven2000** [comment] 2020-12-05 13:45
If this image is your "Computed styles":

https://user-images.githubusercontent.com/45902444/101244242-8b844e00-3705-11eb-9c27-a6bbd7f22368.jpg
![image](https://user-images.githubusercontent.com/6314674/101244729-00ed2000-3700-11eb-903c-d3e579c29074.png)

.. you may have to expand them so the full rule is shown.

**Comment by Vacoas** [comment] 2020-12-05 14:09
It is indeed my "Computed styles". What do I expand exactly ?
    
    Le 05/12/2020 à 14:45, RealRaven2000 a
      écrit :
    
    
      
      If this image is your "Computed styles":
      https://user-images.githubusercontent.com/45902444/101244242-8b844e00-3705-11eb-9c27-a6bbd7f22368.jpg
        
      .. you may have to expand them so the full rule is shown.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-739253028",
"url": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-739253028",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RealRaven2000** [comment] 2020-12-05 14:36
I have taken out the named rule for now - even though it is inherited from the parent element (the button) it may give problems because of higher specificity - see:
https://specifishity.com/

New version below:
[QuickFolders-wx-5.1pre35.zip](https://github.com/RealRaven2000/QuickFolders/files/5647218/QuickFolders-wx-5.1pre35.zip)

I am hoping the missing colors on that element won't matter, but we will see. I can add a class-based rule later.

**Comment by Vacoas** [comment] 2020-12-05 15:00
Version 5.1pre35 does fix the issue. 
    
    The chart to illustrate the concept of specificity is interesting
    and funny. I am afraid it is a bit beyond my grasp but I get the
    general idea.
    
    Would like me to provide some more debugging information ?
    
    Many thanks for your help.
    
    Regards,
    Maurice
    
    Le 05/12/2020 à 15:37, RealRaven2000 a
      écrit :
    
    
      
      I have taken out the named rule for now - even though it is
        inherited from the parent element (the button) it may give
        problems because of higher specificity - see:
        https://specifishity.com/
      New version below:
        QuickFolders-wx-5.1pre35.zip
      I am hoping the missing colors on that element won't matter,
        but we will see. I can add a class-based rule later.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-739258596",
"url": "https://github.com/RealRaven2000/QuickFolders/issues/81#issuecomment-739258596",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RealRaven2000** [comment] 2020-12-07 09:59
> Version 5.1pre35 does fix the issue. The chart to illustrate the concept of specificity is interesting and funny. I am afraid it is a bit beyond my grasp but I get the general idea. Would like me to provide some more debugging information ? Many thanks for your help. Regards, Maurice

No, it's fine. I had to do a few more changes for dark mode to make the standard button (uncolored) text and icons color  work. 
![image](https://user-images.githubusercontent.com/6314674/101336820-d2dc1d00-3872-11eb-99d7-b4a2f2681b06.png)
Here is the latest version for testing:

[QuickFolders-wx-5.1pre42.zip](https://github.com/RealRaven2000/QuickFolders/files/5651884/QuickFolders-wx-5.1pre42.zip)

Installation: download the zip file above. Then drag the file into Thunderbird Add-ons Manager.

PS: Remember if you reply vie email, just cut out all the quoted text at the bottom because otherwise I have edit all your posts which is extra work. I would prefer if you could go to github directly (you can even paste screenshots here) but it's ok if you can't do that.

**Comment by Vacoas** [comment] 2020-12-07 15:46
I have installed 5.1pre42 and performed a number of tests.
So far, I have not encountered any problem.

**Comment by RealRaven2000** [comment] 2020-12-13 10:40
fixed in release 5.1 on 10/Dec/2020

**Closed by RealRaven2000** 2020-12-13 10:40 UTC
