### ISSUE TITLE
quickJump activates open mail tab instead of jumping to Folder in current tab

### ISSUE THREAD

**Issue by PotatoCarl** [RealRaven2000/QuickFolders#389] opened 2023-08-13 05:32 UTC
I have with the latest Pre-Version (the one that offers the filter dialog again) a new issue:
If I enter a folder name in the QuickJump Field and press enter, it jumps to an open Tab in that folder, but not as it is supposed to to the folder view.

**Comment by RealRaven2000** [comment] 2023-08-13 08:01
If there is already a tab open with a folder and you search for it (jump to it) using quickMove, then activating that tab is by design. My thinking behind this is that one may have the tab open for a reason (maybe working on some invoices etc.) and may have forgotten that it is open in another tab for some focused work. While it may be unexpected, there is definitely a reason behind it. Should the behavior be configurable?

**Comment by PotatoCarl** [comment] 2023-08-13 15:56
Absolutely not. I have tabs open to remember the messages and handle them later(hours, days...)
I use Folder Tabs for folders, but open Tabs for emails as a reminder. The folders are in fact different important, frequently used folders.
The behaviour should be configureable, as I personally use quickjump to go to folders (I have hundreds) or sort messages into them/create filters.
I use mail tabs as reminders and folder tabs for a few frequently used folders ("Draft"...).
Thank you.

**Comment by RealRaven2000** [comment] 2023-08-13 17:04
Please distinguish between single mail tabs and folder tabs. It's not quite clear in your answer. jumping to a folder will not open an email tab, but it will "recycle" a folder tab. This is currently "by design" (not a bug) but I can look into adding options to disable this behavior.

**Comment by PotatoCarl** [comment] 2023-08-13 19:29
Actually, QucikJump jumps here to a MAIL TAB (if the mail is in the folder that I want to jump to), NOT to a folder tab (which would be the same as walking down the tree, i.e. no problem).
When I sort an email with QuickJump and there is a Mail Tab in that folder open, I cannot sort it away.
So I have some mail tabs above the quickfolder line folder tabs. When I have an email open in the folder "mailingliste" in the mail tab, then sort from "posteingang" an email via quickjump to "mailingliste", instead of sorting and moving that email, he openes the mail tab (not the folder tab).
This behaviour ocurred with 6.2.

**Comment by RealRaven2000** [comment] 2023-08-13 19:49
ok this description is weird and confusing.
quickJump = Shitf+J and it goes to a folder
quickMove = Shift+M and it moves mails (same as dragging an email to the quickJump / quickMove button
which is it? Can you just provide a step by step description on what you do exactly I am getting confused because you seem to describe 3 different things. Can we just stick to one thing at a time?

**Comment by PotatoCarl** [comment] 2023-08-14 15:45
![grafik](https://github.com/RealRaven2000/QuickFolders/assets/29308597/01f3c7ac-14d3-4d90-84b1-b603f65f0e47)

Move email on the button marked with arrow (where the popupmessag says "QuickJump". Then enter a folder name.

![Screenshot_20230814_174434](https://github.com/RealRaven2000/QuickFolders/assets/29308597/340c59c5-77d7-4201-aac2-bcbf68a28545)

If an email tab with an email in that folder is existing, it jumps to that tab. If not, it sorts into the corresponding folder...

Clearer?

**Comment by RealRaven2000** [comment] 2023-08-14 16:31
ok, I am out of office. I will test that tonight... that behaviour is certainly  not by design. it seems a regression caused by the new tab modes

**Comment by RealRaven2000** [comment] 2023-08-16 09:15
I have tested it and seems to happen once in a session, then not anymore. Stand by I am investigating this further.

**Comment by RealRaven2000** [comment] 2023-08-16 12:19
Ok, did some more testing, but couldn't reproduce it for now, there seems to be some additional condition that triggers it. For the moment, I made a minor fix that avoids throwing an error when I attempt to get the keyboard focus back to the thread pane:

[QuickFolders-mx-6.1.2pre8.zip](https://github.com/RealRaven2000/QuickFolders/files/12359243/QuickFolders-mx-6.1.2pre8.zip)

**Comment by RealRaven2000** [comment] 2023-08-16 12:55
I think I have fixed that now. The code to "reuse open folders" will now only look at the folder URI of tabs in mode "mail3PaneTab", so it will ignore single message tabs.

[QuickFolders-mx-6.1.2pre11.zip](https://github.com/RealRaven2000/QuickFolders/files/12359623/QuickFolders-mx-6.1.2pre11.zip)

----

To test the version above, download the zip file, drag into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment] 2023-08-18 09:51
> I think I have fixed that now. The code to "reuse open folders" will now only look at the folder URI of tabs in mode "mail3PaneTab", so it will ignore single message tabs.

@PotatoCarl does pre 6.1.2pre11(above) fix the issue for you?

**Comment by PotatoCarl** [comment] 2023-08-21 11:24
Yes.
But I am really pissed at the moment at (probably) Thunderbird, as even after installing any "pre" version it takes some time and he goes back to the last stable version. How can I make sure that the pre-version is kept with Thunderbird. I had installed the pre-11 and today was back on 6.1.1.

**Comment by RealRaven2000** [comment] 2023-08-21 12:44
> Yes. But I am really pissed at the moment at (probably) Thunderbird, as even after installing any "pre" version it takes some time and he goes back to the last stable version. How can I make sure that the pre-version is kept with Thunderbird. I had installed the pre-11 and today was back on 6.1.1.

that is really strange / unexpected. everything 6.1.2 necessarily > than 6.1.1 - no idea what's happening on that front.

**Comment by RealRaven2000** [comment] 2023-08-21 14:15
> Yes. But I am really pissed at the moment at (probably) Thunderbird, as even after installing any "pre" version it takes some time and he goes back to the last stable version. How can I make sure that the pre-version is kept with Thunderbird. I had installed the pre-11 and today was back on 6.1.1.

Does this happen immediately when you click "check for updates" on the Extension Manager tools menu?

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/d6c42f1e-875a-428a-8285-6981b1a5312d)

**Comment by PotatoCarl** [comment] 2023-08-21 14:22
Nope. Then it shows "no update found". But sometime later, sometimes one or two days later, it kind of downgrades. No idea where it comes from. But happened several times now. It also does not show any message, but reverts back to the old version.

**Comment by RealRaven2000** [comment] 2023-08-21 16:55
> Nope. Then it shows "no update found". But sometime later, sometimes one or two days later, it kind of downgrades. No idea where it comes from. But happened several times now. It also does not show any message, but reverts back to the old version.

hmmm, never heard of such a behavior before. Some backup / restore / wayback machine / antivirus stuff interfering? I have absolutely no idea, it doesn't sound like it's done by Thunderbird voluntarily....

**Comment by RealRaven2000** [comment] 2023-09-02 09:36
Fixed in 6.2 - Published 30/08/2023

**Closed as completed by RealRaven2000** 2023-09-02 09:36 UTC
Labels: bug
