### ISSUE TITLE
Quickfolders change in format on screen

### ISSUE THREAD

**Issue by cdubleu** [RealRaven2000/QuickFolders#12] opened 2019-11-07 10:41 UTC
The Current Folder Bar which used to display at the top of the message pane now displays at the bottom of the message area after reinstalling Thunderbord and Quickfolders.  Thunderbird Vr.68.2.1 (Mac), Quickfolders Vr. 4.17

Would like to return it to Message Pane as before.

**Comment by RealRaven2000** [comment] 2019-11-07 12:39
Thanks -  had the same report from a different user - I understand it happens only in "Vertical Layout" view, is this correct? (3 columns for folder tree, mail list and preview pane).

- what happens if you switch to a different view (e.g. classic view) and then back to vertical?
- are you using any themes ?
- what other add-ons are installed / active

Currently, I cannot reproduce the behavior the best way would be to look at the structure of screen items in Developer Toolbox / inspector (Ctrl+Shift+I): the element containing the current folder (navigation) toolbar is called `QuickFolders-PreviewToolbarPanel`. 

In my setup this is shown as first element of 
`<vbox id="messagepanebox" ..>` 
(which is a vertical box that also contains the email preview) and as such is displayed on top (before the preview element `<browser id="multimessage" .. >`)

![image](https://user-images.githubusercontent.com/6314674/68389517-08d43c80-015b-11ea-99eb-9f63647474fa.png)

**Comment by cdubleu** [comment] 2019-11-07 19:48
The toolbar shows at the bottom of the mail list in all views whenever I 
switch.
Not using themes
Only two add-ons, Quickfolders and Lightning for calendar and scheduling

Note:  I opened Thunderbird this morning, changed to Vertical View and 
the toolbar showed in the preview pane as it always had before.  Then I 
closed Thunderbird, reopened it and the toolbar returned to the bottom 
of the mail list pane.  I changed views, but the toolbar continued to 
show at the bottom of the preview pane.

For so long before I reinstalled Tbird the Quickfolders Toolbar always 
showed at the top of the preview pane.  Seems to fight all sense that 
the toolbar would change positions in such an erratic way.  I opened the 
inspector, but could not find the hbox id="Quickfolders-Preview..."

Thanks.

**Comment by RealRaven2000** [comment] 2019-11-07 20:04
> I opened the inspector, but could not find the hbox id="Quickfolders-Preview..." 

Can you try what happens when you click on the left-hand side of the current folder toolbar while in inspector? It should bring you to a `<spacer id="QF-CurrentLeftSpacer">` , which is first child of the QuickFolders-PreviewToolbarPanel.

I will try testing by _starting Thunderbird_ in vertical view. Can you avoid the problem by starting Thunderbird in classic view?

**Comment by cdubleu** [comment] 2019-11-07 20:40
As I write this, I am in Vertical View and the toolbar is at the top of 
the Preview Pane.  I finally saw the search function in the Inspector 
and got this.  Hopefully, it helps.

**Comment by cdubleu** [comment] 2019-11-07 21:08
Back again.  I closed TBird while in Vertical.  Reopened and the toolbar 
was back in mail list pane. So, I changed to Classic View and closed 
TBird.  Reopened and toolbar was back at top of Preview Pane!  I did 
this test three more times.  Each time I closed in Vertical toolbar went 
to bottom of mail list pane.  Each time I closed in Classic and reopened 
toolbar move to top of Preview Pane.  Then I would change to Vertical 
View and toolbar stayed at top Preview.  I changed views several times 
and toolbar stayed at top of Preview -- unless I closed in Vertical and 
on startup toolbar would move back to bottom of Mail List pane.

So, as of right now, it seems I must always change to Classic View 
before leaving TBird if I want toolbar to be at top of Preview Pane when 
I change to Vertical (my preferred mode)

Hope this helps.



+++++++++++++++++++

As I write this, I am in Vertical View and the toolbar is at the top of 
the Preview Pane.  I finally saw the search function in the Inspector 
and got this.  Hopefully, it helps.

**Comment by cdubleu** [comment] 2019-11-07 21:12
Forgot to mention, same thing happens when closing and opening in Wide 
View as Vertical View.  Toolbar only goes to top of Preview Pane when I 
open in Classic View.

++++++++++++++++++++++++


Back again.  I closed TBird while in Vertical.  Reopened and the toolbar 
was back in mail list pane. So, I changed to Classic View and closed 
TBird.  Reopened and toolbar was back at top of Preview Pane!  I did 
this test three more times.  Each time I closed in Vertical toolbar went 
to bottom of mail list pane.  Each time I closed in Classic and reopened 
toolbar move to top of Preview Pane.  Then I would change to Vertical 
View and toolbar stayed at top Preview.  I changed views several times 
and toolbar stayed at top of Preview -- unless I closed in Vertical and 
on startup toolbar would move back to bottom of Mail List pane.

So, as of right now, it seems I must always change to Classic View 
before leaving TBird if I want toolbar to be at top of Preview Pane when 
I change to Vertical (my preferred mode)

Hope this helps.



+++++++++++++++++++

As I write this, I am in Vertical View and the toolbar is at the top of 
the Preview Pane.  I finally saw the search function in the Inspector 
and got this.  Hopefully, it helps.

**Comment by RealRaven2000** [comment] 2019-11-07 21:19
that is interesting. I hoped I could reproduce it that way, but it doesn't work for me. If I close in 3 column view the toolbar still appears at the top. Still it may be a pointer to something.... just need to find a "messed up" profile where it works like this. btw I am testing in Tb 68.2.1 at the moment.

**Comment by cdubleu** [comment] 2019-11-07 21:21
I am using 68.2.2

Is there a way to revert to 68.2.1?

**Comment by cdubleu** [comment] 2019-11-07 21:34
I just updated to 68.2.1 on my laptop and it is having same problems my 
desktop is having.

**Comment by RealRaven2000** [comment] 2019-11-28 12:24
Is the issue resolved with the changes in the latest version 4.17.3?

**Comment by RealRaven2000** [comment] 2019-12-03 16:49
Is the issue resolved with the changes in the latest version 4.17.3?

**Comment by RealRaven2000** [comment] 2019-12-23 21:28
resolved in v4.17.3

**Closed by RealRaven2000** 2019-12-23 21:28 UTC
