### ISSUE TITLE
QuickFolders is incompatible with Thunderbird 78.0.

### ISSUE THREAD

**Issue by jtk3000** [RealRaven2000/QuickFolders#53] opened 2020-07-22 15:00 UTC
just did update and got this
QuickFolders is incompatible with Thunderbird 78.0.

**Comment by RealRaven2000** [comment] 2020-07-22 21:44
Please see issue #8 
and the full explanation there. Closing as duplicate.

To roll back to Tb 68, just install over and run the Thunderbird with the command line switches:

` -purgecaches --allow-downgrades`

_from the psa:_

Thunderbird 78 is out, but it is not officially pushed out to users as an automatic update. One of the reasons is that most Add-ons authors are still busy converting their Add-ons to the new Add-ons system. This is the same with all my Add-ons - we are working towards completing a 78 compatible version which will be ready for Thunderbird 78.2 which is going to be pushed to all users automatically around September 2020. With a complicated Add-on like this we still have several weeks of work and testing ahead.

If you have interest or comments in the conversion project please visit the QuickFolders github:

https://github.com/RealRaven2000/QuickFolders/issues/8

Please do not manually upgrade to Thunderbird78 until the issue is resolved. Better yet, wait for the automatic update pushed by Mozilla.

**Closed by RealRaven2000** 2020-07-22 21:44 UTC
