### ISSUE TITLE
list of subfolders not scrolled down

### ISSUE THREAD

**Issue by manniclick** [RealRaven2000/QuickFolders#105] opened 2021-02-02 12:47 UTC
I have highlighted an e-mail and am trying to drag and drop it into a subdirectory. 
when the list of subdirectories exceeds the number of displayable ones and I move the cursor to the lowest position to scroll, no scrolling occurs. 

![2021-02-02 13_46_31-Greenshot](https://user-images.githubusercontent.com/36923799/106602311-1befdb00-655d-11eb-8fb6-1b72f4c8b2dc.png)
![2021-02-02 13_46_23-Greenshot](https://user-images.githubusercontent.com/36923799/106602315-1d210800-655d-11eb-8291-b9141b1436b3.png)

**Comment by RealRaven2000** [comment] 2021-02-02 13:30
This is a duplicate of issue #5 - likely a bug in Thunderbird itself.
AS a workaround try to use the  quickMove button instead. (Drag the mails to the 
![image](https://user-images.githubusercontent.com/6314674/106607024-bac70800-655a-11eb-92aa-b83779a3a890.png) icon or use the keyboard shortcut Shift+M - which can be configured on the last tab of QF settings.

**Comment by manniclick** [comment] 2021-02-02 13:46
I think this is not a real workaronf as I have to specify the Folder. In this case it can be easier to move the emails to the standard folder of TB.
Without a dragged email the scrolling works.

**Comment by RealRaven2000** [comment] 2021-08-31 11:08
Closing as duplicate of #5

For more news & comments on this please use issue #5. Still no idea how to fix this, but I will look into it again. There is literally nobody in the thunderbird core developer team who would be able to help me with this as it is a bug in Mozilla Firefox.

**Closed by RealRaven2000** 2021-08-31 11:08 UTC
