### ISSUE TITLE
Feature request: restrict completion choices to current server

### ISSUE THREAD

**Issue by higham** [RealRaven2000/QuickFolders#118] opened 2021-03-07 21:35 UTC
With QuickJump, QuickMove etc. in the pro version I'd like an option to restrict the completion choices
to the current server.  I have two different email accounts with similar folder structures in Thunderbird.
Nostalgy++ has this feature under the completion preferences.

**Comment by RealRaven2000** [comment] 2021-03-08 11:11
Thanks for the suggestion. There is already a way for hiding folders (and subfolders) from the search results but it can only be applied through a tab and not to a whole account. This would be done via the "Tab specific properties" under QuickFolders commands:
![image](https://user-images.githubusercontent.com/6314674/110312844-892fd980-7ffd-11eb-838a-4cd7fdb6739a.png)

![image](https://user-images.githubusercontent.com/6314674/110312913-a4024e00-7ffd-11eb-9acc-0362ccedbebe.png)

The actual mechanism is stored in QuickFolders "folder string" - so it isn't stored in the folders themselves but in the "tab". If I extend this behavior there would be 2 problems to solve:
1) how to access the "Advanced Properties" setting through the same interface.
2) If these settings are stored without showing the account / server as a tab (which it would have to do with the current UI) - how would the setting be accessed without building a completely new interface.

Existing functionality: 
- You can already configure settings that affect a referenced (by a QF tab) folder and its subfolders. So that would kind of already support the functionality if there was a UI to set it, if I extended it to the "root" folder.
- You can hide tabs via the "Category" setting. So you wouldn't need to have a tab permanently visible for the setting to be applied.

Possible Problems:
- Accounts do not support dragging and dropping. The UI would have to go through either the QuickFolders settings dialog or right-clicking on the account, which is conceivable. I guess Nostalgy has a listbox / dropdown within it's configuration dialog where each account can be selected? Or is it baked into Account settings? modifying account settings (or any window owned by Thunderbird) will become increasingly difficult since legacy Add-ons have been deprecated, so this method may not a good solution for the future.

**Comment by RealRaven2000** [comment] 2021-03-08 13:07
I have started building a prototype, since there is a lot of advanced stuff that can be configured in the search features I think it warrants that it can be in its own dialog box. This will be accessible via "Advanced Settings" under the premium features settings that enable shortcuts:

![image](https://user-images.githubusercontent.com/6314674/110325054-c355a700-800e-11eb-981c-eb8823918c78.png)

the initial dialog looks like this:
![image](https://user-images.githubusercontent.com/6314674/110325172-ebdda100-800e-11eb-8d59-9f82ab00c9e5.png)

I don't want to use a listbox because they are har to extend and won't be html compliant so this would be additional work.
I want to use a grid layout for this so that the checkboxes can align underneath each other without having to make the first row (accounts) a fixed length. For every checkbox there will be a setting stored either as a separate about:config entry or baked into the folder string (which would be nicer but more dangerous for regressions)

**Comment by RealRaven2000** [comment] 2021-03-08 13:13
Once I have a version 1 working I am going to post it here. By the way there are more settings hidden, which can only be configured at the moment by right-clicking the "quickMove" checkbox, which may potentially be added to this UI:
![image](https://user-images.githubusercontent.com/6314674/110325933-e2a10400-800f-11eb-94ca-201a32492b87.png)

![image](https://user-images.githubusercontent.com/6314674/110325948-e896e500-800f-11eb-9172-8e227ae13e1e.png)
These settings are currently undocumented so having a UI will be a good way to make them more accessible and explain them to the users.

**Comment by higham** [comment] 2021-03-08 14:26
Thank you for looking into this, Axel.
Your dialog box doesn't seem to correspond to what I need, though:

When I'm on Account 1 I want Quick* commands to offer only folders on Account 1.
When I'm on Account 2 I want Quick* commands to offer only folders on Account 2.

I don't think your Advance Settings allows this.
So it would just be single dialog box:

"Limit quick* commands to current server".

Having said that, I do sometimes want to copy emails from one account to another
(I just did this and it works perfectly with hundreds of emails),
so the icing on the cake would be to have an easy way to toggle
this setting without going through these menus.

**Comment by RealRaven2000** [comment] 2021-03-08 15:58
> Thank you for looking into this, Axel.
> Your dialog box doesn't seem to correspond to what I need, though:
> 
> When I'm on Account 1 I want Quick* commands to offer only folders on Account 1.
> When I'm on Account 2 I want Quick* commands to offer only folders on Account 2.

That's a problem, because I just built this UI:
![image](https://user-images.githubusercontent.com/6314674/110343928-e3906080-8024-11eb-9748-73fa8e9d9d0d.png)

(note: only works in English locale, as I haven't translated to the other 18 locales yet, but still I thought it was what you wanted) :(
[QuickFolders-wx-5.4pre50.zip](https://github.com/RealRaven2000/QuickFolders/files/6102550/QuickFolders-wx-5.4pre50.zip)

>Having said that, I do sometimes want to copy emails from one account to another (I just did this and it works perfectly with hundreds of emails), so the icing on the cake would be to have an easy way to toggle this setting without going through these menus.

That's actually my main use case. I woulldn't survive without moving stuff across because I am using an old account as my "Local folders". having said that, should it exclude Local Folders as well?

**Comment by fredstluka** [comment] 2021-03-08 23:05
Axel,

That's perfect for me!  I have one primary email account, and bunch of other accounts.  I pretty much NEVER want to file anything away anywhere except the primary account.  But, I DO often move stuff from the other accounts to the primary. 
 So, I'd just check the boxes for all of the other accounts.  Thanks!

--Fred

> I have started building a prototype, since there is a lot of advanced stuff that can be configured in the search features I think it warrants that it can be in its own dialog box. This will be accessible via "Advanced Settings" under the premium features settings that enable shortcuts:
> 
> ![image](https://user-images.githubusercontent.com/6314674/110325054-c355a700-800e-11eb-981c-eb8823918c78.png)
> 
> the initial dialog looks like this:
> ![image](https://user-images.githubusercontent.com/6314674/110325172-ebdda100-800e-11eb-8d59-9f82ab00c9e5.png)

**Comment by RealRaven2000** [comment] 2021-03-09 16:22
Here is a test version. It was bit more difficult because I also had to exclude results from the folder tabs array.
On top is the original feature request (restrict to account of current folder)
Below that is a list of servers that can be excluded from search results:

![image](https://user-images.githubusercontent.com/6314674/110502732-5f58de80-80f3-11eb-93aa-5f424a96e817.png)


[Uploading QuickFolders-wx-5.4pre63.zip…]()

**Comment by fredstluka** [comment] 2021-03-12 20:02
Axel,

Perfect!  I checked the checkboxes for all accounts except my main
one.  Worked exactly as desired.  Thanks!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-03-12 20:30
> Axel, Perfect!  I checked the checkboxes for all accounts except my main one.  Worked exactly as desired.  Thanks!
> […](#)
> --Fred ------------------------------------------------------------------------ Fred Stluka -- http://bristle.com -- Glad to be of service! Open Source: Without walls and fences, we need no Windows or Gates. ------------------------------------------------------------------------

Cool - note that there is no need to check IRC / newsgroups because they will actually not be listen in the final version (see #119 for an up to date version)

**Comment by fredstluka** [comment] 2021-03-12 20:45
Axel,

Does that include RSS feeds?  I AM able to drag email messages
to them, and able to move them there via QuickMove.  I don't
see any reason to change that.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-03-12 21:21
> Axel, Does that include RSS feeds?  I AM able to drag email messages to them, and able to move them there via QuickMove.  I don't see any reason to change that.

I wouldn't think so it's actually based on a server flag:
server.canFileMessagesOnServer

So basically if you cannot copy messages there it's not going to be listed (at least to my own understanding)

**Comment by fredstluka** [comment] 2021-03-13 00:04
Axel,

Sounds perfect!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment] 2021-03-18 13:25
Implemented in 5.4 - Released 18/03/2021

**Comment by RealRaven2000** [comment] 2021-04-17 09:39
I found a bug - when I activate the restriction to the current server I still see suggestions to create new subfolders on other servers if only parent matches are found - logging this in #140

**Comment by RealRaven2000** [comment] 2021-04-19 14:04
Closing as #140 is now also addressed in the latest official releases (5.5 and 4.21.2)

**Closed by RealRaven2000** 2021-04-19 14:04 UTC
Labels: enhancement
