### ISSUE TITLE
Version 5.10 not compatible with Thunderbird 78.14.0

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#276] opened 2022-06-14 07:55 UTC
![floating-screenshot-092608](https://user-images.githubusercontent.com/26068595/173523217-28b4e5f3-7710-4040-8c0b-5ce12ecc128e.jpg)

![floating-screenshot-094033](https://user-images.githubusercontent.com/26068595/173523290-1422624e-802a-4f93-bf8a-ec2708fee3cf.jpg)

![floating-screenshot-094430](https://user-images.githubusercontent.com/26068595/173523357-5f697075-8078-473a-b355-b36d547d5799.jpg)

The reinstallation leads me to used the previous version.

However version 5.10pre27 is functional...

**Comment by RealRaven2000** [comment] 2022-07-29 14:58
I just installed 78 here again, trying to find an issue that I couldn't reproduce. do you happen to know which one it was? The OP used some ...pre3 version IIRC.

**Comment by macdeport** [comment] 2022-07-29 19:12
Thank you for reinstalling Thunderbird 78.14.0 (the last version I can use).

I have both licenses for QuickFolders Pro and for SmartTemplate Pro working together but at this time my main trouble come from images not displayed in SmartTemplate Forward.

**Comment by RealRaven2000** [comment] 2022-07-30 10:01
> Thank you for reinstalling Thunderbird 78.14.0 (the last version I can use).
> 
> I have both licenses for QuickFolders Pro and for SmartTemplate Pro working together but at this time my main trouble come from images not displayed in SmartTemplate Forward.

Alright, for reference, the issue is here:

https://github.com/RealRaven2000/SmartTemplates/issues/203

If there are no major breaking problems with QuickFolders 5.9.1 in Thunderbird 78 I am going to close this issue now.

**Closed by RealRaven2000** 2022-07-30 10:01 UTC
Labels: question
