### ISSUE TITLE
Moving emails from different folders doesn't remove them from the queue

### ISSUE THREAD

**Issue by pierresw2** [RealRaven2000/QuickFolders#328] opened 2022-12-01 07:55 UTC
Moving multiple emails from different folders into another folder works, but the QuickMove icon still displays them as 'active' after the move. The number of emails in the queue is still displayed on the icon.

Doesn't happen when multiple emails are dragged simultaneously onto the QuickMove icon. In that case, everything works fine.

**Comment by RealRaven2000** [comment] 2022-12-01 10:46
Thanks for reporting! I was always wondering whether any users actually used the feature of "accumulating" mails from different start folders to move to a common target; so this one is quite a hard one to find! I will look into it and post a quick fix here soon.

**Comment by pierresw2** [comment] 2022-12-01 10:58
Thanks a lot!
And yes, I use it a lot this way. 
Most common use-case for me: I answer an email from the inbox, then move both the original mail (from the inbox) and my answer (from the sent folder) to a project folder.

**Comment by RealRaven2000** [comment] 2022-12-01 11:08
> Thanks a lot! And yes, I use it a lot this way. Most common use-case for me: I answer an email from the inbox, then move both the original mail (from the inbox) and my answer (from the sent folder) to a project folder.

Alright - if you do this a lot - I may be able to save you some time there. You should try out the Add-on [Copy Sent to Current](https://addons.thunderbird.net/en-US/thunderbird/addon/copy-sent-to-current/?src=ss), which will actually move your reply into the same folder you replied from. No more unnecessary round trips to the sent folder!

it's especially  helpful if you like looking at your emails in "threaded view". You can reply directly from a target folder (e.g. if you have a filter set up to move mails to topical / sender folders) and the thread will stay together like in a gmail "all mail" view, but without having the clutter of a full Inbox.

**Comment by RealRaven2000** [comment] 2022-12-01 13:58
Here is a new test version. Apparently when I call the `MailServices.copy.copyMessages()` I cannot have differing source folders, even if you see that it worked for you the function throws an error - and I hadn't handled this part correctly. I decided to break up the array into single messages, calling copyMessages() multiple times. Might give some performance problems when moving a large number (e.g. 500 messages) from the same folder, which would be more efficient by calling once and passing an array of message ids. I might write some optimizing code to re-package all messages from the same source folder into collated arrays to have less calls, but you shouldn't experience any performance loss if you only move 2 messages. Thanks to @jobisoft for helping me find the cause of the problem.

[QuickFolders-mx-5.14.1pre8.zip](https://github.com/RealRaven2000/QuickFolders/files/10132948/QuickFolders-mx-5.14.1pre8.zip)

to install this version, download the zip file and drag into QuickFolders Add-ons Manager (do not unpack contents).

**Comment by pierresw2** [comment] 2022-12-01 14:01
You're scary quick!
Performance isn't an issue for me since I usually move only 2-5 messages (max 10) at a time. Will test pronto and let you know!

**Comment by RealRaven2000** [comment] 2022-12-01 14:21
> EDIT: **Works fine, thanks!**

thanks for testing - fix will go into the next version. Your test version will automatically update, as usual.

**Comment by RealRaven2000** [comment] 2022-12-01 14:27
Reopening, sorry I should have explained - I will close the issues myself when I release the code officially to avoid duplicates and help other users. (In default view, the issues page only shows open issues)

**Comment by RealRaven2000** [comment] 2022-12-22 11:24
Implemented in 5.15.1 - Published 22/Dec/2022

**Closed by RealRaven2000** 2022-12-22 11:24 UTC
Labels: bug
