### ISSUE TITLE
Subfolder menu does not scroll when dragging email and list of folders is longer than fits on screen

### ISSUE THREAD

**Issue by swolh** [RealRaven2000/QuickFolders#67] opened 2020-10-31 12:24 UTC
When dragging an email to the "Recent Folders" or the "Inbox" tabs, the list of subfolders expands, but when you have more subfolders than will fit on the screen (top to bottom), and you try to drag the email to the arrow at the bottom to get the list to scroll and show a folder not initially shown, the list does not scroll.

**Comment by RealRaven2000** [comment] 2020-11-12 17:27
Duplicate of issue #5
https://github.com/RealRaven2000/QuickFolders/issues/5

**Closed by RealRaven2000** 2020-11-12 17:27 UTC
