### ISSUE TITLE
Folders have disappeared in tabs

### ISSUE THREAD

**Issue by EddyGC** [RealRaven2000/QuickFolders#334] opened 2022-12-23 00:36 UTC
I must state, I am not a programmer, just a user.

Recently TB updated to 102.6.1. This was followed (yesterday) by QF updating to 5.15.

As a result all subfolders, in fact everything under each tab has now disappeared when I right-click on a tab (see image). I can click on the tab and it will take me to the folder.

I have absolutely no idea what to do next and repair this very useful piece of software.

![image](https://user-images.githubusercontent.com/45447971/209248119-c1504ce2-ee78-4a2d-b5a1-8ca1e1bba980.png)

**Comment by RealRaven2000** [comment] 2022-12-23 11:46
This is a duplicate of #333 (see detail there) - and has been fixed in QuickFolders 5.15.1. The best action is to update QuickFolders via Tools / Addons & Themes:

![image](https://user-images.githubusercontent.com/6314674/209330896-d742aaf0-2999-47b5-97a0-3f4405e5cf3f.png)

**Comment by EddyGC** [comment] 2022-12-24 00:39
Thank you. It has fixed the problem

**Comment by RealRaven2000** [comment] 2023-02-20 17:32
Fixed in 5.15.1

**Closed by RealRaven2000** 2023-02-20 17:32 UTC
