### ISSUE TITLE
"Current Folder Bar" doesn't show current subfolders when left-clicked

### ISSUE THREAD

**Issue by stratosjl** [RealRaven2000/QuickFolders#268] opened 2022-06-03 09:12 UTC
- When I right-click on the folder name in the bar, it shows its subfolders. 
- When I left-click on the folder name, it shows a long list of folders, but I can't tell the criterion by which they appear. They are mixed-level (top, second, etc) folders and the list is always the same, no matter where I am at the moment. 
- When I click "go to next sibling folder", it goes to the next folder, but repeated clicking will jump apparently randomly to same-level folders, not in the way that they appear in the folder tree pane on the left. 

Using v.5.10pre27

**Comment by stratosjl** [comment] 2022-06-03 09:19
Upgraded to TB 91.10 and point no2 above has been fixed. Point no 3 still exists, but I don't mind much.

**Comment by RealRaven2000** [comment] 2022-06-03 14:16
> * When I right-click on the folder name in the bar, it shows its subfolders.
> * When I left-click on the folder name, it shows a long list of folders, but I can't tell the criterion by which they appear. They are mixed-level (top, second, etc) folders and the list is always the same, no matter where I am at the moment.

(In Betterbird 91.10) I can confirm the subfolder list is not being updated when left-clicking on the "Current Folder Bar" - I suspect it shows an old list from an earlier folder (possibly the first time clicked in a Thunderbird session)

> * When I click "go to next sibling folder", it goes to the next folder, but repeated clicking will jump apparently randomly to same-level folders, not in the way that they appear in the folder tree pane on the left.

It uses the order that is passed back by the folder array (it is not alphabetically sorted as the subfolders menus that I create) - I haven't found a way of forcing Thunderbird to give me the exact order from the tree.

**Comment by stratosjl** [comment] 2022-06-04 05:14
> Upgraded to TB 91.10 and point no2 above has been fixed. Point no 3 still exists, but I don't mind much.

Nope, it's still there. You're right, it only works the first time you left-click during a TB session. After that, it shows the same list for the rest of the session.

**Comment by RealRaven2000** [comment] 2022-06-07 16:01
Here is a test version with quick fix. turns out I have to regenerate the popupId.

[QuickFolders-mx-5.10pre31.zip](https://github.com/RealRaven2000/QuickFolders/files/8854766/QuickFolders-mx-5.10pre31.zip)

**Comment by RealRaven2000** [comment] 2022-06-13 21:56
Fixed in 5.10 - Published 13/06/2022

**Closed by RealRaven2000** 2022-06-13 21:56 UTC
Labels: bug
